import {expect,it} from 'vitest';
import {memoryDriver} from './db-helper';
import {migrate} from '../src/core/db/migrate';
import {repository} from '../src/core/db/repository';
import {hash,normalizeRow} from '../src/ingest/normalize';
import type {Document,ImportContext} from '../src/ingest/types';
const context:ImportContext={accountId:'a',accountKind:'checking',currency:'AUD',period:{start:'2026-01-01',end:'2026-01-31'},dateOrder:'DMY',decimal:'.',creditPositivePurchases:false};
function document(name:string):Document{return {id:hash(JSON.stringify(['a',hash(name)])),hash:hash(name),fileName:name,parser:'synthetic-test',context,opening:'10000',closing:'9000',payslip:null,rows:[{...normalizeRow({sourceId:'1',date:'2026-01-02',description:'Synthetic store',amount:'-10.00',confidence:10000},context),category:'Shopping',verified:true}]};}
async function setup(){const {driver}=memoryDriver();await migrate(driver);const repo=repository(driver);await repo.addAccount({id:'a',name:'Synthetic',institution:'',type:'checking',currency:'AUD',mask_last4:null,opening_balance_minor:0n});return {repo,driver};}
it('keeps category edits across corroboration and rollback without altering source evidence',async()=>{const {repo,driver}=await setup(),one=document('one'),two=document('two');await repo.imports.stage(one);await repo.imports.commit(one.id);const id=(await repo.imports.ledger())[0]!.id;const sources=await driver.query('SELECT * FROM transaction_sources');await repo.categories.set([id],'Groceries');expect((await repo.imports.ledger())[0]?.category).toBe('Groceries');expect(await driver.query('SELECT * FROM transaction_sources')).toEqual(sources);await repo.imports.stage(two);await repo.imports.commit(two.id);await repo.imports.rollback(one.id);expect((await repo.imports.ledger())[0]?.category).toBe('Groceries');await repo.imports.rollback(two.id);expect(await repo.imports.ledger()).toEqual([]);await repo.imports.stage(one);await repo.imports.commit(one.id);expect((await repo.imports.ledger())[0]?.category).toBe('Groceries');await repo.categories.set([id],null);expect((await repo.imports.ledger())[0]?.category).toBeNull();expect((await repo.imports.ledger())[0]?.minor).toBe('-1000');});
it('validates the complete selection before changing anything and retains edits through backup',async()=>{const {repo}=await setup(),doc=document('one');await repo.imports.stage(doc);await repo.imports.commit(doc.id);const id=(await repo.imports.ledger())[0]!.id;await expect(repo.categories.set([id,'missing'],'Groceries')).rejects.toThrow('removed');expect((await repo.imports.ledger())[0]?.category).toBe('Shopping');await repo.categories.set([id],'Health');const empty=memoryDriver();await migrate(empty.driver);const restored=repository(empty.driver);await restored.restoreBackup(await repo.exportAll());expect((await restored.imports.ledger())[0]?.category).toBe('Health');});
