import { describe, expect, it } from 'vitest';
import fc from 'fast-check';
import { migrate } from '../src/core/db/migrate';
import { repository } from '../src/core/db/repository';
import { memoryDriver } from './db-helper';
import { canonicalMerchant, hash, normalizeAmount, normalizeDate, normalizeRow, shiftDay } from '../src/ingest/normalize';
import { balance, coverage, coveredDays, dailyAverage, gaps, reconcile, totals } from '../src/ingest/reconcile';
import { csvRows, inferColumns, parseTable } from '../src/ingest/parse/csv';
import { parseOfx, parseQif } from '../src/ingest/parse/structured';
import { parsePayslip, payCycle, payMetrics } from '../src/ingest/parse/payslip';
import { positionalTable } from '../src/ingest/parse/positional';
import { detect } from '../src/ingest/detect';
import { categorize } from '../src/ledger/rules';
import type { Document, ImportContext } from '../src/ingest/types';
const context: ImportContext = { accountId: 'a', accountKind: 'checking', currency: 'AUD', period: { start: '2026-01-01', end: '2026-03-31' }, dateOrder: 'DMY', decimal: '.', creditPositivePurchases: false };
function statement(name: string, first: number, last: number, value = -100n, accountId = 'a'): Document {
  const c = { ...context, accountId, period: { start: shiftDay('2026-01-01', first), end: shiftDay('2026-01-01', last) } };
  const rows = Array.from({ length: last - first + 1 }, (_, i) => normalizeRow({ sourceId: String(i), date: shiftDay(c.period.start, i), description: `SYNTHETIC SHOP ${i + first}`, amount: '1.00', direction: value < 0n ? 'debit' : 'credit', confidence: 10000 }, c)).map(r => { return normalizeRow({ sourceId: r.sourceId, date: r.date, description: r.description, amount: `${value < 0n ? '-' : ''}${(value < 0n ? -value : value) / 100n}.${((value < 0n ? -value : value) % 100n).toString().padStart(2, '0')}`, confidence: 10000 }, c); });
  const fileHash = hash(name); return { id: hash(JSON.stringify([accountId, fileHash])), hash: fileHash, fileName: name, parser: 'synthetic-test-v1', context: c, opening: '0', closing: (value * BigInt(rows.length)).toString(), rows, payslip: null };
}
const orders = [[0, 1, 2], [0, 2, 1], [1, 0, 2], [1, 2, 0], [2, 0, 1], [2, 1, 0]];
async function setup() { const db = memoryDriver(); await migrate(db.driver); const repo = repository(db.driver); for (const id of ['a', 'b']) await repo.addAccount({ id, name: 'Synthetic ' + id, institution: 'Synthetic', type: 'checking', currency: 'AUD', mask_last4: null, opening_balance_minor: 0n }); return { ...db, repo }; }
async function accept(repo: ReturnType<typeof repository>, doc: Document) { await repo.imports.stage(doc); const review = await repo.imports.review(doc.id); for (const { row, blocked } of review.items) if (blocked) await repo.imports.correct(doc.id, row.sourceId, row, false); await repo.imports.commit(doc.id); }
describe('Import normalization and pure parsers', () => {
  it.each([['1,234.56', '.', 123456n], ['1.234,56', ',', 123456n], ['(123.45)', '.', -12345n], ['123.45 DR', '.', -12345n], ['123.45 CR', '.', 12345n], ['123.45-', '.', -12345n]] as const)('reads %s exactly', (s, separator, result) => expect(normalizeAmount(s, 'AUD', separator)).toBe(result));
  it('rejects ambiguous grouping, excess decimals and contradictory signs', () => { for (const s of ['1,23.45', '12.345', '-12.00 CR', '1.2.3', 'NaN']) expect(() => normalizeAmount(s, 'AUD', '.')).toThrow(); });
  it('handles year rollover and refuses ambiguous or invalid dates', () => { const period = { start: '2025-12-15', end: '2026-01-15' }; expect(normalizeDate('02/01', period, 'DMY')).toBe('2026-01-02'); expect(normalizeDate('31/12', period, 'DMY')).toBe('2025-12-31'); expect(() => normalizeDate('31/02/2026', context.period, 'DMY')).toThrow(); });
  it('inverts credit purchases without double-inverting debit/credit columns', () => { const c = { ...context, accountKind: 'credit' as const, creditPositivePurchases: true }; const raw = { sourceId: '1', date: '2026-01-01', description: 'Synthetic purchase', amount: '10.00', confidence: 10000 }; expect(normalizeRow(raw, c).minor).toBe('-1000'); expect(normalizeRow({ ...raw, direction: 'credit' }, c).minor).toBe('1000'); });
  it('uses aliases only for a clear fuzzy winner', () => { expect(canonicalMerchant('EFTPOS COLES STORE 123 MELBOURNE VIC', [{ canonical: 'COLES', aliases: [] }])).toBe('COLES'); });
  it('parses quoted CSV and all three generic column layouts', () => { for (const csv of ['Date,Description,Amount\n01/01/2026,"Synthetic, shop",-1.00', 'Posted date;Details;Debit;Credit\n01/01/2026;Synthetic shop;1,00;', 'Merchant\tTransaction date\tValue\nSynthetic shop\t01/01/2026\t-1.00']) expect(parseTable(csvRows(csv))).toHaveLength(1); expect(() => csvRows('a,b\n"unfinished')).toThrow(); expect(() => inferColumns(['x', 'y'])).toThrow('Map'); });
  it('reads OFX and QIF without converting money to floating point', () => { expect(parseOfx('<OFX><BANKTRANLIST><STMTTRN><DTPOSTED>20260101<TRNAMT>-12.34<FITID>abc<NAME>Synthetic</STMTTRN></BANKTRANLIST></OFX>')[0]?.amount).toBe('-12.34'); expect(parseQif('!Type:Bank\nD01/01/2026\nT-12.34\nPSynthetic\n^')[0]?.amount).toBe('-12.34'); });
  it('stitches a repeated positional header across a page break', () => { const items = [1, 2].flatMap(page => ['Date', 'Description', 'Amount'].map((text, i) => ({ text, x: i * 150, y: 10, width: 80, page })).concat([`0${page}/01/2026`, 'Synthetic', '-1.00'].map((text, i) => ({ text, x: i * 150, y: 30, width: 80, page })))); expect(positionalTable(items)).toHaveLength(2); expect(positionalTable(items, true).every(r => r.confidence < 9000)).toBe(true); });
  it('detects actual file signatures and returns actionable unknown-format errors', () => { expect(detect(new TextEncoder().encode('%PDF-1.7'), 'unknown').kind).toBe('pdf'); expect(() => detect(new Uint8Array([0, 1]), 'unknown.bin')).toThrow('Choose'); });
  it('applies rules before defaults and keeps heuristic suggestions uncertain', () => { const row = statement('a', 0, 0).rows[0]!; expect(categorize(row, [{ id: 'r', priority: 1, merchant: row.merchant, category: 'Health' }], { [row.merchant]: 'Food' }).category).toBe('Health'); expect(categorize({ ...row, merchant: 'COLES' }, []).confidence).toBeLessThan(9000); });
});
describe('Reconciliation invariants against real SQLite', () => {
  it('produces byte-identical canonical ledger state for all six overlapping import orders', async () => {
    await fc.assert(fc.asyncProperty(fc.bigInt({ min: -1000000n, max: -1n }), async value => {
      const docs = [statement('one', 0, 20, value), statement('two', 7, 27, value), statement('three', 14, 34, value)]; let expected: string | undefined;
      for (const order of orders) { const { repo, raw, driver } = await setup(); for (const i of order) await accept(repo, docs[i]!); const state = JSON.stringify({ ledger: await driver.query('SELECT * FROM transactions ORDER BY id'), sources: await driver.query('SELECT * FROM transaction_sources ORDER BY transaction_id,import_batch_id,source_row_id'), coverage: await driver.query('SELECT * FROM coverage_ranges ORDER BY id') }); expected ??= state; expect(state).toBe(expected); expect((await repo.imports.ledger()).length).toBe(35); raw.close(); }
    }), { numRuns: 15, seed: 208 });
  }, 60000);
  it('keeps staging isolated, skips the identical file and rejects balance mismatch', async () => { const { repo, raw, driver } = await setup(); const doc = statement('one', 0, 20); await repo.imports.stage(doc); expect(await driver.query('SELECT * FROM transactions')).toEqual([]); await accept(repo, doc); expect(await repo.imports.stage(doc)).toEqual({ id: doc.id, alreadyImported: true }); expect((await repo.imports.commit(doc.id)).added).toBe(0); const broken = { ...statement('bad', 25, 26), closing: '999' }; await repo.imports.stage(broken); expect((await repo.imports.review(broken.id)).doc.status).toBe('quarantined'); await expect(repo.imports.commit(broken.id)).rejects.toThrow('Balance'); expect((await repo.imports.ledger()).length).toBe(21); raw.close(); });
  it('rolls back batch two without changing batches one and three', async () => { const docs = [statement('one', 0, 20), statement('two', 7, 27), statement('three', 14, 34)]; const a = await setup(), b = await setup(); for (const doc of docs) await accept(a.repo, doc); await a.repo.imports.rollback(docs[1]!.id); for (const i of [0, 2]) await accept(b.repo, docs[i]!); for (const table of ['transactions', 'transaction_sources', 'coverage_ranges', 'merchants', 'categories']) expect(await a.driver.query(`SELECT * FROM ${table} ORDER BY 1,2,3`)).toEqual(await b.driver.query(`SELECT * FROM ${table} ORDER BY 1,2,3`)); a.raw.close(); b.raw.close(); });
  it('excludes only a uniquely matched internal transfer from both totals', () => { const a = statement('a', 0, 0, -10000n), b = statement('b', 0, 0, 10000n, 'b'); a.rows[0]!.description = 'TRANSFER TO SAVINGS'; b.rows[0]!.description = 'TRANSFER FROM EVERYDAY'; const ledger = reconcile([a, b]); expect(ledger.every(r => r.transferGroup)).toBe(true); expect(totals(ledger, 'AUD')).toEqual({ income: 0n, spending: 0n }); b.rows[0]!.description = 'SALARY'; a.rows[0]!.description = 'SHOP'; expect(reconcile([a, b]).every(r => !r.transferGroup)).toBe(true); });
  it('rolls back a failed commit transaction without a partial ledger or rule', async () => {
    const { repo, driver, raw } = await setup(); const one = statement('original', 0, 0); await accept(repo, one); const next = statement('interrupted', 20, 21); await repo.imports.stage(next);
    for (const item of (await repo.imports.review(next.id)).items) await repo.imports.correct(next.id, item.row.sourceId, { ...item.row, category: 'Groceries' }, true);
    const before = await driver.query('SELECT * FROM transactions ORDER BY id');
    const broken = repository({ ...driver, execute: async (sql, values) => { if (sql.startsWith('INSERT INTO transaction_sources')) throw new Error('Synthetic storage interruption'); return driver.execute(sql, values); } });
    await expect(broken.imports.commit(next.id)).rejects.toThrow('Synthetic storage interruption');
    expect(await driver.query('SELECT * FROM transactions ORDER BY id')).toEqual(before); expect((await repo.imports.review(next.id)).doc.status).toBe('staged'); expect(await driver.query('SELECT * FROM rules')).toEqual([]); raw.close();
  });
  it('prefers a confirmed settled row over a pending duplicate and restores pending on rollback', async () => {
    const { repo, raw } = await setup(); const pending = statement('pending', 0, 0); pending.context.period.end = '2026-01-31'; pending.rows[0]!.pending = true; pending.rows[0]!.issues = ['Pending row']; await accept(repo, pending);
    const posted = statement('posted', 2, 2); posted.context.period.start = '2026-01-01'; posted.context.period.end = '2026-01-31'; posted.rows = [normalizeRow({ sourceId: '0', date: '2026-01-03', description: pending.rows[0]!.description, amount: '-1.00', confidence: 10000 }, posted.context)];
    await repo.imports.stage(posted); expect((await repo.imports.review(posted.id)).uncertainCount).toBe(1); const target = (await repo.imports.ledger())[0]!;
    await repo.imports.correct(posted.id, '0', { ...posted.rows[0]!, duplicateOf: target.id }, false); await repo.imports.commit(posted.id);
    const rows = await repo.imports.ledger(); expect(rows).toHaveLength(1); expect(rows[0]?.pending).toBe(false); expect(rows[0]?.date).toBe('2026-01-03'); await repo.imports.rollback(posted.id); expect((await repo.imports.ledger())[0]?.pending).toBe(true); raw.close();
  });
  it('links payslip net pay without adding salary or statement coverage twice', async () => {
    const { repo, driver, raw } = await setup(); const salary = statement('salary', 14, 14, 160000n); await accept(repo, salary);
    const doc = statement('payslip', 0, 30); doc.rows = []; doc.payslip = parsePayslip('Employer: Synthetic employer\nPay date: 15/01/2026\nPeriod start: 01/01/2026\nPeriod end: 14/01/2026\nGross: 2000.00\nNet: 1600.00\nTax: 400.00\nSuper: 240.00', context);
    await accept(repo, doc); expect((await repo.imports.ledger())).toHaveLength(1); expect((await driver.query('SELECT linked_transaction_id FROM payslips'))[0]?.linked_transaction_id).toBe((await repo.imports.ledger())[0]!.id); expect(await driver.query('SELECT * FROM coverage_ranges')).toHaveLength(1); await repo.imports.rollback(salary.id); expect((await driver.query('SELECT linked_transaction_id FROM payslips'))[0]?.linked_transaction_id).toBe(null); raw.close();
  });
  it('shows a missing week and excludes it from averages', () => { const ranges = [{ start: '2026-01-01', end: '2026-01-07' }, { start: '2026-01-15', end: '2026-01-21' }]; expect(gaps(ranges, { start: '2026-01-01', end: '2026-01-21' })).toEqual([{ start: '2026-01-08', end: '2026-01-14' }]); expect(coveredDays(ranges)).toBe(14); expect(dailyAverage(1400n, ranges)).toBe(100n); expect(coverage([...ranges, ranges[0]!])).toEqual(ranges); });
  it('requires confirmation of collisions and creates rules only at commit', async () => { const { repo, driver, raw } = await setup(); const doc = statement('collision', 0, 0); doc.rows.push({ ...doc.rows[0]!, sourceId: 'other' }); doc.closing = '-200'; await repo.imports.stage(doc); await expect(repo.imports.commit(doc.id)).rejects.toThrow('uncertain'); for (const row of doc.rows) await repo.imports.correct(doc.id, row.sourceId, { ...row, occurrence: row.sourceId, category: 'Groceries' }, true); expect(await driver.query('SELECT * FROM rules')).toEqual([]); await repo.imports.commit(doc.id); expect((await repo.imports.ledger()).length).toBe(2); expect((await driver.query('SELECT * FROM rules')).length).toBe(2); await repo.imports.rollback(doc.id); expect(await driver.query('SELECT * FROM rules')).toEqual([]); expect(await driver.query('SELECT * FROM merchants')).toEqual([]); raw.close(); });
});
describe('Payslips', () => {
  it('extracts labelled pay data and derives rates and cycle from three distinct dates', () => { const p = parsePayslip('Employer: Synthetic employer\nPay date: 15/01/2026\nPeriod start: 01/01/2026\nPeriod end: 14/01/2026\nGross: 2000.00\nNet: 1600.00\nTax: 400.00\nSuper: 240.00\nYTD Gross: 12000.00', context); expect(p.net).toBe('160000'); expect(p.ytd.Gross).toBe('1200000'); const pays = [p, { ...p, payDate: '2026-01-29' }, { ...p, payDate: '2026-02-12' }]; expect(payCycle(pays)).toBe('fortnightly'); expect(payMetrics(pays).takeHomeBasisPoints).toBe(8000n); expect(payCycle([p, p, p])).toBe('insufficient_data'); expect(balance({ ...statement('pay', 0, 0), rows: [], payslip: p }).valid).toBe(true); });
});
