import {fixture} from './intelligence-fixtures';
import {describe,it,expect} from 'vitest';
import {forecast,goalFunding,payRise,payCycle,scheduledDates} from '../src/intelligence/forecast';
describe('Session 3 evidence contract',()=>{
 it('forecast quantiles remain ordered and pending debits reduce safe spending once',()=>{const s=fixture();const a=forecast(s,'20000');expect(a.status).toBe('ok');for(const h of a.horizons){expect(BigInt(h.low)<=BigInt(h.middle)&&BigInt(h.middle)<=BigInt(h.high)).toBe(true);}s.transactions.push({...s.transactions[0]!,id:'pending',minor:'-10000',status:'pending'});const b=forecast(s,'20000');expect(BigInt(b.horizons[0]!.middle)).toBe(BigInt(a.horizons[0]!.middle)-10000n);expect(BigInt(b.safeDaily!)).toBeLessThan(BigInt(a.safeDaily!));});
 it('scenarios and per-pay funding derive exact integer amounts',()=>{const s=fixture();const a=forecast(s,'0'),b=forecast(s,'0',{extraBill:'8000'});expect(BigInt(a.horizons[0]!.middle)-BigInt(b.horizons[0]!.middle)).toBe(8000n);expect(goalFunding('10000','0','2026-08-01',s.asOf,['2026-07-10','2026-07-24'])).toBe('5000');});
 it('missing or stale balance produces no confident forecast',()=>{const s=fixture();s.liquid!.asOf='2026-06-01';expect(forecast(s,'0').status).toBe('insufficient_data');});
 it('pay-rise proposal requires sustained comparable pay periods',()=>{const s=fixture();s.pays.slice(-3).forEach(p=>p.net='120000');expect(payRise(s)[0]!.suggested).toBe('10000');s.pays.at(-1)!.start='2026-01-01';expect(payRise(s)).toEqual([]);});
});
it('reserves outstanding credit liability and blocks unknown loan commitments',()=>{const s=fixture(),a=forecast(s,'0');s.committedLiability={minor:'10000',evidence:['credit-balance']};const b=forecast(s,'0');expect(BigInt(a.horizons[0]!.middle)-BigInt(b.horizons[0]!.middle)).toBe(10000n);s.commitmentsKnown=false;expect(forecast(s,'0').status).toBe('insufficient_data');});

it('monthly pay preserves month-end while four-weekly pay remains interval-based',()=>{const s=fixture();s.asOf='2026-03-31';s.pays=s.pays.slice(0,3).map((p,i)=>({...p,date:['2026-01-31','2026-02-28','2026-03-31'][i]!}));const c=payCycle(s)[0]!;expect(c.next).toBe('2026-04-30');expect(scheduledDates(c,'2026-06-30')).toEqual(['2026-04-30','2026-05-31','2026-06-30']);s.pays.forEach((p,i)=>p.date=['2026-02-03','2026-03-03','2026-03-31'][i]!);expect(payCycle(s)[0]!.next).toBe('2026-04-28');});
