import {expect,it} from 'vitest';
import {currency} from '../src/core/money';
import {paydayCurve,subscriptionTimeline} from '../src/intelligence/visuals/timing';
import type {Snapshot,Transaction} from '../src/intelligence/model';
const aud=currency('AUD');
function snapshot():Snapshot{return {asOf:'2026-03-31',currency:aud,accountIds:['a'],coverage:[{accountId:'a',start:'2026-01-01',end:'2026-03-31',tier:'C'}],pays:['2026-01-01','2026-02-01','2026-03-01'].map((date,i)=>({id:String(i),employer:'Synthetic',date,start:date,end:date,net:'200000',gross:'250000',currency:aud,transactionId:null})),transactions:[]};}
function transaction(id:string,date:string):Transaction{return {id,accountId:'a',date,minor:'-1000',currency:aud,description:'Synthetic membership',category:'Leisure',kind:'discretionary',status:'settled',transfer:false,recurring:true};}
it('divides by covered observations and never substitutes missing days with zero',()=>{const s=snapshot(),w={start:'2026-03-01',end:'2026-03-03',label:'March'};s.transactions=[transaction('one','2026-03-01'),{...transaction('pending','2026-03-01'),status:'pending'}, {...transaction('transfer','2026-03-01'),transfer:true}];const result=paydayCurve(s,w);expect(result.points[0]).toMatchObject({average:'1000',days:1,ids:['one']});expect(result.points[1]?.average).toBe('0');s.coverage[0]!.start='2026-03-02';expect(paydayCurve(s,w).points[0]?.average).toBeNull();s.pays.pop();expect(paydayCurve(s,w).status).toBe('insufficient_data');});
it('shows actual recurring payments, without inventing events between observations',()=>{const s=snapshot();s.transactions=['2026-01-05','2026-02-05','2026-03-05'].map((date,i)=>transaction(String(i),date));const result=subscriptionTimeline(s,{start:'2026-01-01',end:'2026-03-31',label:'Quarter'});expect(result).toHaveLength(1);expect(result[0]!.events.map(e=>e.date)).toEqual(['2026-01-05','2026-02-05','2026-03-05']);s.transactions[1]!.status='pending';expect(subscriptionTimeline(s,{start:'2026-01-01',end:'2026-03-31',label:'Quarter'})).toEqual([]);});
