// Generated by scripts/tokens.mjs. Edit the source palette, not this file.
export const THEMES = [
  {id: 'dark', label: 'Dark', scheme: 'dark', background: '#08090A', swatch: {surface: '#0E1011', ink: '#EDEEF0', accent: '#5B7CFA'}},
  {id: 'light', label: 'Light', scheme: 'light', background: '#FCFCFD', swatch: {surface: '#FFFFFF', ink: '#14171A', accent: '#3B5BDB'}},
  {id: 'black', label: 'True black', scheme: 'dark', background: '#000000', swatch: {surface: '#0A0B0C', ink: '#EDEEF0', accent: '#5B7CFA'}},
  {id: 'paper', label: 'Paper', scheme: 'light', background: '#EFE9DF', swatch: {surface: '#F6F2EA', ink: '#221E1A', accent: '#3450BE'}},
  {id: 'contrast', label: 'High contrast', scheme: 'light', background: '#FFFFFF', swatch: {surface: '#FFFFFF', ink: '#000000', accent: '#1E3CB4'}},
] as const;
export type ThemeId = typeof THEMES[number]['id'];
