import {abs,covered,dates,day,historical,median,shift,sum,type Snapshot} from '../model';
type Schedule={interval:number;next:string;monthly?:{anchor:string;monthEnd:boolean}|undefined};
function monthlyPattern(ds:string[]):Schedule['monthly']{const last=ds.slice(-3);if(last.length<3)return undefined;const parsed=last.map(d=>new Date(d+'T00:00:00Z')),months=parsed.map(d=>d.getUTCFullYear()*12+d.getUTCMonth());if(months[1]!==months[0]!+1||months[2]!==months[1]!+1)return undefined;const ends=parsed.every(d=>d.getUTCDate()===new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate());return ends||new Set(parsed.map(d=>d.getUTCDate())).size===1?{anchor:last[2]!,monthEnd:ends}:undefined;}
function monthlyDate(m:NonNullable<Schedule['monthly']>,offset:number){const anchor=new Date(m.anchor+'T00:00:00Z'),last=new Date(Date.UTC(anchor.getUTCFullYear(),anchor.getUTCMonth()+offset+1,0));return new Date(Date.UTC(last.getUTCFullYear(),last.getUTCMonth(),m.monthEnd?last.getUTCDate():Math.min(anchor.getUTCDate(),last.getUTCDate()))).toISOString().slice(0,10);}
function nextDate(last:string,interval:number,asOf:string,monthly:Schedule['monthly']){let n=1,next=monthly?monthlyDate(monthly,n):shift(last,interval);while(next<=asOf){n++;next=monthly?monthlyDate(monthly,n):shift(next,interval);}return next;}
export function scheduledDates(s:Schedule,through:string):string[]{const out:string[]=[];let next=s.next,offset=1;while(next<=through&&out.length<1000){out.push(next);if(s.monthly){while(monthlyDate(s.monthly,offset)<=next)offset++;next=monthlyDate(s.monthly,offset);}else next=shift(next,s.interval);}return out;}
export type Recurrence={merchant:string;minor:string;interval:number;next:string;evidence:string[];monthly?:Schedule['monthly']};
/**
 * A REPEAT IS PROVED BY THE PAYMENTS THEMSELVES, not by whether a statement covered the days between.
 *
 * `historical` keeps only statement-covered days, which is right for anything that divides by a number
 * of days: you cannot average over days you never observed. A recurrence divides by nothing — three
 * payments a fortnight apart are a fortnightly bill whoever recorded them — and a ledger typed in by
 * hand has no coverage at all, so the forecast saw no bills for someone who has no statements. It still
 * demands coverage, because its own figures are per-day; `requireCoverage:false` is for the advice that
 * only needs to know what is due.
 */
export function recurrences(s:Snapshot,options:{requireCoverage?:boolean}={}):Recurrence[]{const window={start:shift(s.asOf,-179),end:s.asOf,label:''};const seen=options.requireCoverage===false?s.transactions.filter(t=>t.currency===s.currency&&s.accountIds.includes(t.accountId)&&t.status==='settled'&&!t.transfer&&t.kind!=='transfer'&&t.date>=window.start&&t.date<=window.end):historical(s,window);const groups=new Map<string,Snapshot['transactions']>();for(const t of seen.filter(t=>BigInt(t.minor)<0n)){const key=t.description.trim().toLowerCase();groups.set(key,[...(groups.get(key)??[]),t]);}const out:Recurrence[]=[];for(const [merchant,rows] of groups){rows.sort((a,b)=>a.date.localeCompare(b.date));if(rows.length<3)continue;const last=rows.slice(-3),interval=day(last[2]!.date)-day(last[1]!.date),prior=day(last[1]!.date)-day(last[0]!.date);if(interval<6||interval>32||Math.abs(interval-prior)>3)continue;const amount=median(last.map(t=>abs(BigInt(t.minor))));if(last.some(t=>abs(abs(BigInt(t.minor))-amount)*100n>amount*10n))continue;const monthly=monthlyPattern(last.map(t=>t.date)),next=nextDate(last[2]!.date,interval,s.asOf,monthly);out.push({merchant,minor:amount.toString(),interval,next,monthly,evidence:last.map(t=>t.id)});}return out;}
export function payCycle(s:Snapshot){const employers=[...new Set(s.pays.filter(p=>p.currency===s.currency).map(p=>p.employer))];return employers.flatMap(employer=>{const ps=s.pays.filter(p=>p.currency===s.currency&&p.employer===employer&&p.date<=s.asOf).sort((a,b)=>a.date.localeCompare(b.date));if(ps.length<3)return [];const gaps=ps.slice(1).map((p,i)=>day(p.date)-day(ps[i]!.date));const interval=Math.round(Number(median(gaps.map(BigInt)).toString()));if(interval<1||interval>40)return [];const monthly=monthlyPattern(ps.map(p=>p.date)),next=nextDate(ps.at(-1)!.date,interval,s.asOf,monthly);return [{employer,interval,next,monthly,pays:ps,irregular:!monthly&&gaps.some(g=>Math.abs(g-interval)>3)}];});}
export type Forecast={status:'ok'|'insufficient_data';reason:string;assumptions:string[];evidence:string[];horizons:{days:number;low:string;middle:string;high:string}[];safeDaily:string|null;nextPay:string|null;committed:string;pending:string;buffer:string;recurrences:Recurrence[]};
export function forecast(s:Snapshot,buffer:string,scenario:{extraBill?:string;cutPercent?:number}={}):Forecast{
 const result:Forecast={status:'insufficient_data',reason:'A current balance, 60 covered days, and at least three payslips per income source are needed.',assumptions:[],evidence:[],horizons:[],safeDaily:null,nextPay:null,committed:'0',pending:'0',buffer,recurrences:[]};
 const start=shift(s.asOf,-89),valid=dates({start,end:s.asOf,label:''}).filter(d=>covered(s,d)),pay=payCycle(s);if(!s.liquid||s.liquid.asOf!==s.asOf||valid.length<60||!pay.length||s.commitmentsKnown===false)return result;
 const cut=scenario.cutPercent??0;if(!Number.isInteger(cut)||cut<0||cut>100||BigInt(buffer)<0n||BigInt(scenario.extraBill??'0')<0n)throw new Error('Use non-negative amounts and a reduction between 0 and 100.');
 const rs=recurrences(s),recurringIds=new Set(rs.flatMap(r=>r.evidence));const rows=historical(s,{start,end:s.asOf,label:''});
 // Exclude all observations of identified recurring merchants from residual daily spend.
 const names=new Set(rs.map(r=>r.merchant));const residual=sum(rows.filter(t=>BigInt(t.minor)<0n&&!names.has(t.description.trim().toLowerCase())).map(t=>-BigInt(t.minor)))/BigInt(valid.length);
 const pending=sum(s.transactions.filter(t=>t.currency===s.currency&&t.status==='pending'&&!t.transfer&&BigInt(t.minor)<0n).map(t=>-BigInt(t.minor)));
 const next=pay.map(p=>p.next).sort()[0]!,n=day(next)-day(s.asOf);const bills=(h:number)=>sum(rs.map(r=>{const count=scheduledDates(r,shift(s.asOf,h)).length;return BigInt(r.minor)*BigInt(count);})) + BigInt(scenario.extraBill??'0');
 const income=(h:number,which:'low'|'middle'|'high')=>sum(pay.map(p=>{const a=p.pays.map(x=>BigInt(x.net)).sort((a,b)=>a<b?-1:a>b?1:0);const value=which==='low'?a[Math.floor((a.length-1)/4)]!:which==='high'?a[Math.floor((a.length-1)*3/4)]!:median(a);return value*BigInt(scheduledDates(p,shift(s.asOf,h)).length);}));
 const anchor=BigInt(s.liquid.minor)-pending-BigInt(s.committedLiability?.minor??'0');const residualAfter=residual*BigInt(100-cut)/100n;const committed=bills(n);const safe=anchor-committed-BigInt(buffer);
 Object.assign(result,{status:'ok',reason:'',safeDaily:(safe>0n?safe/BigInt(n):0n).toString(),nextPay:next,committed:committed.toString(),pending:pending.toString(),recurrences:rs,evidence:[...new Set([...rows.map(t=>t.id),...recurringIds,...s.liquid.evidence,...(s.committedLiability?.evidence??[]),...pay.flatMap(p=>p.pays.flatMap(x=>x.transactionId?[x.transactionId]:[]))])],assumptions:['Income uses empirical lower quartile, median and upper quartile of imported net pay; these are scenarios, not confidence intervals.','Recurring dates and amounts repeat; residual spending uses only covered days.','Known outstanding credit liabilities are reserved in full; missing loan commitments prevent a safe-to-spend estimate.','Safe-to-spend excludes the next pay receipt and reserves committed bills, pending debits and the chosen buffer exactly once.',`Scenario: residual spending reduced ${cut}%; extra one-off commitment ${scenario.extraBill??'0'} minor units.`,...(s.liquid.verified?[]:['Balance unverified: this projection is provisional.']),...(pay.some(p=>p.irregular)?['Irregular pay dates: future dates are an observed-interval assumption.']:[])]});
 result.horizons=[30,60,90].map(days=>{const end=anchor-bills(days)-residualAfter*BigInt(days);return {days,low:(end+income(days,'low')).toString(),middle:(end+income(days,'middle')).toString(),high:(end+income(days,'high')).toString()};});return result;
}
export function goalFunding(target:string,funded:string,targetDate:string,asOf:string,payDates:string[]):string|null{if(BigInt(target)<0n||BigInt(funded)<0n||day(targetDate)<day(asOf))throw new Error('Choose a future goal date and non-negative amounts.');const n=payDates.filter(d=>d>asOf&&d<=targetDate).length;if(!n)return null;const remaining=BigInt(target)-BigInt(funded);return remaining>0n?((remaining+BigInt(n)-1n)/BigInt(n)).toString():'0';}
export function payRise(s:Snapshot){return payCycle(s).flatMap(c=>{const ps=c.pays;if(ps.length<6)return [];const earlier=ps.slice(-6,-3),latest=ps.slice(-3);const duration=(p:typeof ps[number])=>day(p.end)-day(p.start)+1;if(new Set([...earlier,...latest].map(duration)).size!==1)return [];const before=median(earlier.map(p=>BigInt(p.net))),after=median(latest.map(p=>BigInt(p.net)));if(before<=0n||latest.some(p=>BigInt(p.net)*100n<before*105n))return [];return [{employer:c.employer,increment:(after-before).toString(),suggested:((after-before)/2n).toString(),evidence:[...earlier,...latest].map(p=>p.id),action:'If the higher pay continues at your next payday, consider reserving half of the increase for your chosen goal.',assumption:'Comparable pay periods, not proof of an hourly-rate rise; confirm hours and bonuses.',researchId:'save-more-tomorrow'}];});}
