import {sum,type Snapshot,type Signal} from '../model';
import {distress} from '../profile';
export const claimResearch={small_leaks:'pain-of-paying',recurring_review:'mental-accounting',payday_plan:'present-bias',buffer_first:'scarcity'} as const;
export type Insight={id:string;kind:keyof typeof claimResearch;signal:Signal['key'];threshold:string;evidence:string[];title:string;body:string;action:string;researchId:string;projectedMinor:string;assumption:string;ease:number;triage:boolean;inputs:{baseMinor:string;numerator:string;denominator:string}};
export function insights(s:Snapshot,signals:Signal[],dismissals:Record<string,number>={}):Insight[]{
 const out:Insight[]=[];const add=(kind:Insight['kind'],v:Signal,threshold:string,title:string,body:string,action:string,base:bigint,n:bigint,d:bigint,evidence:string[],triage=false)=>{if(!evidence.length||base<=0n||(dismissals[kind]??0)>=2)return;out.push({id:`v1:${s.currency}:${v.period}:${kind}`,kind,signal:v.key,threshold,evidence,title,body,action,researchId:claimResearch[kind],projectedMinor:(base*n/d).toString(),assumption:`Scenario only: ${n*100n/d}% of the selected spending is retained over an equivalent covered period. No guaranteed saving.`,ease:triage?3:2,triage,inputs:{baseMinor:base.toString(),numerator:n.toString(),denominator:d.toString()}});};
 const low=distress(s,signals);
 for(const v of signals.filter(x=>x.status==='ok')){
  const evidence=s.transactions.filter(t=>v.evidence.includes(t.id)&&t.status==='settled'&&!t.transfer&&t.currency===s.currency&&BigInt(t.minor)<0n);
  if(low){if(v.key==='small_leak_index')add('buffer_first',v,'buffer <5 days, rising recorded high-interest debt or repeated recorded overdraft fees','Make room for essentials','Review one small commitment before making a new plan.','If another small discretionary purchase comes up, pause it and reserve that amount for essentials.',sum(evidence.map(t=>-BigInt(t.minor))),1n,10n,evidence.map(t=>t.id),true);continue;}
  if(v.key==='small_leak_index'&&BigInt(v.details.count??'0')>=10n&&BigInt(v.details.share??'0')>=1000n)add('small_leaks',v,'at least 10 small purchases and 10% of discretionary spending','Small purchases add up',`${v.details.count} purchases below the displayed small-ticket limit are in this evidence. A purchase is not automatically a mistake.`,'If you are about to repeat one of these purchases, check your remaining plan before paying.',BigInt(v.details.total??'0'),1n,5n,v.evidence);
  if(v.key==='subscription_drag'&&BigInt(v.value!)>=2000n){const recurring=evidence.filter(t=>t.recurring);add('recurring_review',v,'recurring spend ≥20% of recorded net income','Review recurring commitments','Recurring spending reaches the review threshold; confirm which commitments you still want.','If a listed renewal is due, check whether you still use it before it renews.',sum(recurring.map(t=>-BigInt(t.minor))),1n,10n,recurring.map(t=>t.id));}
  if(v.key==='payday_decay'&&BigInt(v.value!)>=5000n)add('payday_plan',v,'days 1–3 spend / remainder ≥0.5 across ≥2 complete cycles','Plan the first days after pay','Spending clusters near recorded pay dates. This does not establish impulsive intent.','If your next pay arrives, reserve a chosen amount for later-cycle commitments first.',BigInt(v.details.early??'0'),1n,10n,v.evidence);
 }
 return out.sort((a,b)=>{const x=BigInt(a.projectedMinor)*BigInt(a.ease),y=BigInt(b.projectedMinor)*BigInt(b.ease);return x>y?-1:x<y?1:a.id.localeCompare(b.id);}).slice(0,low?1:3);
}
