import { DatabaseSync } from 'node:sqlite';
import { readFileSync, writeFileSync } from 'node:fs';
const db = new DatabaseSync(':memory:');
db.exec(readFileSync('src/core/db/migrations/0001_foundation.up.sql', 'utf8'));
db.exec(readFileSync('src/core/db/migrations/0002_query_indexes.up.sql', 'utf8'));
let md = '# Current data model\n\nSchema version: 2. Generated by `npm run schema` from canonical SQL migrations.\n\nMoney columns are signed INTEGER minor units, restricted to the JavaScript/native bridge exact integer range ±9,007,199,254,740,991. All arithmetic occurs in bigint. Positive is credit; negative is debit, including credit-account purchases. Confidence uses integer basis points (0–10000). JSON money is decimal integer strings when nested in JSON fields. Dates use ISO text; import normalization validates calendar dates against the statement period.\n\nDrizzle models typed queries. SQL migrations enforce the complete constraints and foreign keys. Baseline rollback is destructive and explicitly guarded; subsequent migrations are reversible without deleting records. Coverage rows retain source provenance; union/gap functions exclude uncovered days from averages. transaction_sources retains every contributing batch, so shared transactions can survive a batch rollback.\n\n';
for (const { name } of db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all()) {
 md += `## ${name}\n\n| Column | Storage | Required | Default |\n|---|---|---|---|\n`;
 for (const col of db.prepare(`PRAGMA table_info(${name})`).all()) md += `| ${col.name} | ${col.type} | ${col.notnull ? 'Yes' : 'No'} | ${col.dflt_value ?? '—'} |\n`;
 const fks=db.prepare(`PRAGMA foreign_key_list(${name})`).all();
 if(fks.length) md+='\nReferences: '+fks.map(f=>`${f.from} → ${f.table}.${f.to} (${f.on_delete})`).join('; ')+'.\n';
 md+='\n';
}
md+='## Import staging payloads\n\nReserved source row `__file__` contains a user-selected file as base64 in encrypted SQLite until extraction or discard. Reserved `__document__` contains the complete normalized document, account context, stated balances and optional payslip. Ordinary source rows contain editable normalized transactions and their issues. Committed documents remain available for deterministic rollback; these are not duplicate live ledger entries. Corrections can carry deferred merchant rules applied only at commit.\n\n';
md+='## Migration metadata\n\n`_migrations(version INTEGER PRIMARY KEY)` is maintained transactionally by the migration runner. It is not financial data and is removed with the database during deletion.\n';
writeFileSync('docs/SCHEMA.md',md); db.close();
