import { mkdirSync, writeFileSync } from 'node:fs';
export const palettes = {
 dark: {'surface-0':'#08090A','surface-1':'#0E1011','surface-2':'#16191B','surface-3':'#1F2325','text-primary':'#EDEEF0','text-secondary':'#9BA1A6','text-tertiary':'#63696E','accent':'#5B7CFA','positive':'#3FB950','negative':'#E5534B','warning':'#D29922','text-meta':'#969DA3','accent-text':'#9BABFF','accent-solid':'#435BC8','on-accent':'#FFFFFF','positive-text':'#67CB79','negative-text':'#FF9691','warning-text':'#E7B957','border-control':'#707980','heat-1':'#242E55','heat-2':'#293869','heat-3':'#3B51A2','heat-4':'#4E6BD4','heat-5':'#8098FF','heat-ink-1':'#FFFFFF','heat-ink-2':'#FFFFFF','heat-ink-3':'#FFFFFF','heat-ink-4':'#FFFFFF','heat-ink-5':'#08090A','flow-in':'#C4813C','flow-out':'#5B7CFA','flow-in-fill':'#916B3C','flow-out-fill':'#4A5FA8','tile-1':'#252D46','tile-2':'#2E3859','tile-3':'#3A4877','tile-4':'#485895','tile-5':'#5A6DAE','tile-ink':'#FFFFFF'},
 light: {'surface-0':'#FCFCFD','surface-1':'#FFFFFF','surface-2':'#F4F5F6','surface-3':'#EAECEE','text-primary':'#14171A','text-secondary':'#5C6469','text-tertiary':'#8B9296','accent':'#3B5BDB','positive':'#25763A','negative':'#B52D2C','warning':'#805900','text-meta':'#60686E','accent-text':'#324DBB','accent-solid':'#3B5BDB','on-accent':'#FFFFFF','positive-text':'#216C35','negative-text':'#B52D2C','warning-text':'#785300','border-control':'#7C848B','heat-1':'#D3DCF7','heat-2':'#BFCCF4','heat-3':'#8EA4EA','heat-4':'#4C6BD6','heat-5':'#2B45B8','heat-ink-1':'#14171A','heat-ink-2':'#14171A','heat-ink-3':'#14171A','heat-ink-4':'#FFFFFF','heat-ink-5':'#FFFFFF','flow-in':'#96500F','flow-out':'#3B5BDB','flow-in-fill':'#B08A5C','flow-out-fill':'#7D8CC6','tile-1':'#DCE2F0','tile-2':'#C7D0E7','tile-3':'#ABB7D8','tile-4':'#8998C3','tile-5':'#7787AE','tile-ink':'#14171A'},
};
const linear=v=>v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4;
const rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);
export function contrast(a,b) {const lum=h=>{const [r,g,b]=rgb(h).map(linear);return 0.2126*r+0.7152*g+0.0722*b;};const l=[lum(a),lum(b)].sort((a,b)=>b-a);return (l[0]+0.05)/(l[1]+0.05);}
function oklch(hex){
 const [r,g,b]=rgb(hex).map(linear);
 const l=Math.cbrt(.4122214708*r+.5363325363*g+.0514459929*b),m=Math.cbrt(.2119034982*r+.6806995451*g+.1073969566*b),s=Math.cbrt(.0883024619*r+.2817188376*g+.6299787005*b);
 const L=.2104542553*l+.793617785*m-.0040720468*s,A=1.9779984951*l-2.428592205*m+.4505937099*s,B=.0259040371*l+.7827717662*m-.808675766*s;
 return `oklch(${(L*100).toFixed(5)}% ${Math.hypot(A,B).toFixed(6)} ${((Math.atan2(B,A)*180/Math.PI+360)%360).toFixed(4)})`;
}
let css='/* Generated by scripts/tokens.mjs. Edit the source palette, not this file. */\n';
let report='# Contrast verification\n\nWCAG 2.x sRGB relative luminance ratios, evaluated against every surface. All body text uses accessible aliases. Raw tertiary tokens are retained from the brief but never used for text. Decorative dividers are exempt; input boundaries use border-control. Ratios below are minima across surfaces 0–3.\n\n| Theme | Pair | Minimum ratio | Required | Result |\n|---|---|---:|---:|---|\n';
let failed=false;
for (const [theme,tokens] of Object.entries(palettes)) {
 css+=`[data-theme="${theme}"] {\n  color-scheme: ${theme};\n`;
 for(const [key,value] of Object.entries(tokens))css+=`  --${key}: ${oklch(value)};\n`;
 const ink=theme==='dark'?'100% 0 0':'0% 0 0';
 css+=`  --border-subtle: oklch(${ink} / 0.06);\n  --border-default: oklch(${ink} / 0.11);\n}\n`;
 for(const key of ['text-primary','text-secondary','text-meta','accent-text','positive-text','negative-text','warning-text','border-control']){
  const ratio=Math.min(...[0,1,2,3].map(n=>contrast(tokens[key],tokens[`surface-${n}`]))); const required=key==='border-control'?3:4.5;
  if(ratio<required)failed=true;
  report+=`| ${theme} | ${key} / surfaces | ${ratio.toFixed(2)} | ${required} | ${ratio>=required?'PASS':'FAIL'} |\n`;
 }
 const ratio=contrast(tokens['on-accent'],tokens['accent-solid']);if(ratio<4.5)failed=true;
 report+=`| ${theme} | on-accent / accent-solid | ${ratio.toFixed(2)} | 4.5 | ${ratio>=4.5?'PASS':'FAIL'} |\n`;
 report+=`| ${theme} | Requested raw tertiary / surface-0 (unused for text) | ${contrast(tokens['text-tertiary'],tokens['surface-0']).toFixed(2)} | 4.5 | N/A — replaced by text-meta |\n`;
}
mkdirSync('src/ui/design',{recursive:true});mkdirSync('docs',{recursive:true});
writeFileSync('src/ui/design/tokens.css',css);writeFileSync('docs/CONTRAST.md',report);
if(failed)throw new Error('Contrast gate failed. Fix palette aliases.');
