import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {editableCategories} from '../../ledger/categories';
import {money} from '../../core/money';
import {Amount,Button,Input,Row,Sheet} from '../design/primitives';
import {useSession} from '../session';
export function BulkCategories({onClose}:{onClose:()=>void}){
 const session=useSession(),query=useQueryClient(),[search,setSearch]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<Set<string>>(new Set()),[category,setCategory]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 // Matched and bounded in SQL: the sheet already caps selection at 1,000 rows, so the whole
 // ledger never crosses the native bridge to fill it.
 const candidates=useQuery({queryKey:['bulk-categories',search],queryFn:()=>session.run(repo=>repo.imports.ledgerBulk(search)),enabled:session.state==='ready',placeholderData:previous=>previous});
 const filtered=candidates.data?.rows??[],matching=candidates.data?.total??0,shown=filtered.slice(page*50,(page+1)*50);
 async function save(){setBusy(true);setError('');try{await session.run(repo=>repo.categories.set([...selected],category||null));await query.invalidateQueries();onClose();}catch(e){setError(e instanceof Error?e.message:'Categories could not be saved. Your selection is unchanged.');}finally{setBusy(false);}}
 return <Sheet title="Change categories" onClose={()=>{if(!busy)onClose();}}><div className="stack"><p>Choose imported transactions to update together. Amounts and source statements stay unchanged. Matched transfers are excluded.</p><Input label="Filter transactions to categorise" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><div className="form-actions"><Button disabled={busy||matching>1000} onClick={()=>setSelected(new Set(filtered.map(r=>r.id)))}>Select matching rows</Button><Button disabled={busy} onClick={()=>setSelected(new Set())}>Clear selection</Button></div><p className="meta">{selected.size} selected · {matching} matching. Narrow the filter for more than 1,000 rows.</p>{shown.map(r=><Row key={r.id} trailing={<Amount value={money(BigInt(r.minor),r.currency)} context={r.merchant}/>}><label className="check-row"><input type="checkbox" disabled={busy||(!selected.has(r.id)&&selected.size>=1000)} checked={selected.has(r.id)} onChange={()=>setSelected(previous=>{const next=new Set(previous);if(next.has(r.id))next.delete(r.id);else next.add(r.id);return next;})}/><span>{r.merchant}<span className="meta"> · {r.date} · {r.category??'Uncategorised'}</span></span></label></Row>)}<div className="form-actions"><Button disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>Previous rows</Button><Button disabled={(page+1)*50>=filtered.length||busy} onClick={()=>setPage(p=>p+1)}>Next rows</Button></div><label className="input-label">Apply category<select value={category} disabled={busy} onChange={e=>setCategory(e.target.value)}><option value="">Leave uncategorised</option>{editableCategories.map(c=><option key={c}>{c}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<Button variant="primary" disabled={busy||!selected.size} onClick={()=>void save()}>Save categories</Button></div></Sheet>;
}
