import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FileUp, FileCheck2 } from 'lucide-react';
import type { Account, Repository } from '../../core/db/repository';
import { currency, currencyDigits, format, money } from '../../core/money';
import { buildDocument } from '../../ingest/pipeline';
import { decodeFile, selectFiles } from '../../ingest/review/files';
import { merchantName, normalizeAmount } from '../../ingest/normalize';
import { coverage, coveredDays, dataHealth, gaps } from '../../ingest/reconcile';
import type { Batch, ImportContext, LedgerRow, NormalizedRow } from '../../ingest/types';
import { ImportFailure } from '../../ingest/types';
import type { Columns } from '../../ingest/parse/csv';
import { payMetrics } from '../../ingest/parse/payslip';
import { Amount, Button, EmptyState, Input, Row, Sheet } from '../design/primitives';
import { useSession } from '../session';
const categoryNames = ['Groceries', 'Housing', 'Utilities', 'Transport', 'Health', 'Eating out', 'Shopping', 'Entertainment', 'Income', 'Transfer', 'Savings', 'Debt'];
function decimalString(minor: string, code: string): string { const value = BigInt(minor), digits = currencyDigits[currency(code)], unit = 10n ** BigInt(digits), absolute = value < 0n ? -value : value; return `${value < 0n ? '-' : ''}${absolute / unit}${digits ? '.' + (absolute % unit).toString().padStart(digits, '0') : ''}`; }
type Review = Awaited<ReturnType<Repository['imports']['review']>>;
function Failure({ error }: { error: Error }) { return <div className="import-failure" role="alert">{error instanceof ImportFailure && <><p>{error.understood}</p><pre>{error.excerpt}</pre></>}<p>{error.message}</p></div>; }
export function ImportWorkspace({ accounts, request, consumed }: { accounts: Account[]; request: number; consumed: () => void }) {
  const session = useSession(), query = useQueryClient();
  const [fileId, setFileId] = useState<string | null>(null), [reviewId, setReviewId] = useState<string | null>(null), [transaction, setTransaction] = useState<LedgerRow | null>(null), [undo, setUndo] = useState<Batch | null>(null), [search, setSearch] = useState(''), [page, setPage] = useState(0), [notice, setNotice] = useState('');
  const data = useQuery({ queryKey: ['imports'], queryFn: () => session.run(async repo => ({ files: await repo.imports.files(), batches: await repo.imports.batches(), ledger: await repo.imports.ledger() })), enabled: session.state === 'ready' });
  const pick = useMutation({ mutationFn: () => session.run(selectFiles), onSuccess: async count => { setNotice(count ? `${count} files staged. Confirm the account and statement details for each file.` : 'No files selected.'); await query.invalidateQueries({ queryKey: ['imports'] }); } });
  const requestHandled = useRef(false);
  useEffect(() => { if (!request) requestHandled.current = false; if (request && !requestHandled.current && session.state === 'ready') { requestHandled.current = true; consumed(); pick.mutate(); } }, [request]); // Request is a one-shot navigation action.
  const rollback = useMutation({ mutationFn: (id: string) => session.run(repo => repo.imports.rollback(id)), onSuccess: async () => { setUndo(null); await query.invalidateQueries(); setNotice('Import rolled back. Other statement sources are retained.'); } });
  const rows = data.data?.ledger ?? [], batches = data.data?.batches ?? [], files = data.data?.files ?? [];
  const filtered = rows.filter(row => `${row.description} ${row.date} ${row.category ?? ''}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date) || a.id.localeCompare(b.id));
  return <section className="import-workspace"><div className="form-actions"><Button variant="primary" disabled={!accounts.length || pick.isPending || session.state !== 'ready'} onClick={() => pick.mutate()}><FileUp size={16}/>{pick.isPending ? 'Selecting files…' : 'Import statements'}</Button></div>
    {!accounts.length && <p className="meta">Set up an account before choosing statements.</p>}{notice && <p role="status" className="notice">{notice}</p>}{pick.error && <Failure error={pick.error}/>} {data.error && <Failure error={data.error}/>}
    {files.length > 0 && <section className="section-gap"><h2>Files waiting for review</h2><p>These files are encrypted on your device. Nothing enters your ledger until you confirm.</p>{files.map(file => <Row key={file.id} trailing={<Button onClick={() => setFileId(file.id)}>Read file</Button>}>{file.name}</Row>)}</section>}
    {batches.length > 0 && <section className="section-gap"><h2>Imports</h2>{batches.map(batch => <Row key={batch.id} trailing={batch.status === 'committed' ? <Button onClick={() => setUndo(batch)}>Roll back</Button> : batch.status === 'rolled_back' ? <span className="meta">Rolled back</span> : <Button onClick={() => setReviewId(batch.id)}>Review</Button>}><h3>{batch.fileName}</h3><p>{batch.status === 'quarantined' ? 'Balance mismatch · quarantined' : batch.status === 'staged' ? 'Awaiting your confirmation' : batch.status === 'committed' ? 'Committed' : 'Removed from ledger'}</p></Row>)}</section>}
    <section className="section-gap"><h2>Transactions</h2><Input label="Search transactions" placeholder="Merchant, date or category" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }}/>{filtered.length ? <>{filtered.slice(page * 50, (page + 1) * 50).map(row => <button type="button" className="transaction-row" key={row.id} onClick={() => setTransaction(row)}><span><strong>{row.merchant}</strong><span className="meta">{row.date} · {row.transferGroup ? 'Internal transfer' : row.category ?? 'Uncategorised'}</span></span><Amount value={money(BigInt(row.minor), row.currency)} context={row.merchant}/></button>)}<div className="form-actions"><Button disabled={page === 0} onClick={() => setPage(p => p - 1)}>Previous</Button><span className="meta">{filtered.length} {filtered.length === 1 ? 'transaction' : 'transactions'}</span><Button disabled={(page + 1) * 50 >= filtered.length} onClick={() => setPage(p => p + 1)}>Next</Button></div></> : <EmptyState icon={<FileCheck2 size={24}/>} title={search ? 'No matching transactions' : 'No transactions yet'} action={search ? <Button onClick={() => setSearch('')}>Clear search</Button> : <Button disabled={!accounts.length || pick.isPending || session.state !== 'ready'} onClick={() => pick.mutate()}>Choose statements</Button>}>Import a statement, review its rows, then confirm the import.</EmptyState>}</section>
    {accounts.map(account => <Coverage key={account.id} account={account} batches={batches} rows={rows}/>)}
    {batches.some(b => b.status === 'committed' && b.payslip) && <section className="section-gap"><h2>Payslips</h2>{accounts.map(account => { const pays = batches.filter(b => b.status === 'committed' && b.context.accountId === account.id).flatMap(b => b.payslip ? [b.payslip] : []); if (!pays.length) return null; const metrics = payMetrics(pays); return <div key={account.id}><h3>{account.name}</h3><Row trailing={<span>{metrics.cycle.replaceAll('_', ' ')}</span>}>Detected pay cycle</Row><p className="meta">At least three distinct pay dates are needed. Payslips link to ledger income; they never add a second salary transaction.</p>{pays.map((p, i) => <Row key={i} trailing={<Amount value={money(BigInt(p.net), p.currency)} context="Payslip net pay"/>}>{p.employer}<p>{p.payDate} · Net pay</p></Row>)}</div>; })}</section>}
    {fileId && <FileReview id={fileId} accounts={accounts} onClose={() => setFileId(null)} onStaged={id => { setFileId(null); setReviewId(id); }}/>} {reviewId && <BatchReview id={reviewId} onClose={() => setReviewId(null)}/>}
    {transaction && <Sheet title="Source transaction" onClose={() => setTransaction(null)}><div className="stack"><Amount value={money(BigInt(transaction.minor), transaction.currency)} context={transaction.merchant}/><p>{transaction.date} · {accounts.find(a => a.id === transaction.accountId)?.name}</p><pre className="raw-excerpt">{transaction.description}</pre><p>{transaction.transferGroup ? 'Matched internal transfer. Excluded from income and spending.' : transaction.category ?? 'Uncategorised'}</p><h3>Supporting statements</h3>{transaction.sources.map(s => <p key={s.batchId + s.sourceId}>{batches.find(b => b.id === s.batchId)?.fileName} · row {s.sourceId}</p>)}</div></Sheet>}
    {undo && <Sheet title="Roll back this import?" onClose={() => { if (!rollback.isPending) setUndo(null); }}><div className="stack"><p>{undo.fileName}</p><p>Remove this statement’s contribution. Transactions supported by other committed statements remain. Rules created by this import are removed with it.</p>{rollback.error && <Failure error={rollback.error}/>}<Button variant="danger" disabled={rollback.isPending} onClick={() => rollback.mutate(undo.id)}>Confirm rollback</Button></div></Sheet>}
  </section>;
}
function Coverage({ account, batches, rows }: { account: Account; batches: Batch[]; rows: LedgerRow[] }) {
  const ranges = coverage(batches.filter(b => b.status === 'committed' && !b.payslip && b.context.accountId === account.id).map(b => b.context.period));
  if (!ranges.length) return null;
  const window = { start: ranges[0]!.start, end: ranges.at(-1)!.end }, missing = gaps(ranges, window), health = dataHealth(rows.filter(r => r.accountId === account.id), ranges, window);
  return <section className="section-gap coverage"><h2>{account.name} coverage</h2><p>{coveredDays(ranges)} covered days · {health.coveragePercent}% of {window.start}–{window.end}</p><div className="coverage-map" role="img" aria-label={`${account.name}: ${coveredDays(ranges)} covered days, ${missing.length} gaps`}>{[...ranges.map(r => ({ ...r, covered: true })), ...missing.map(r => ({ ...r, covered: false }))].sort((a, b) => a.start.localeCompare(b.start)).map(r => <span className={r.covered ? 'covered-range' : 'missing-range'} key={r.start} style={{ flex: coveredDays([r]) }} title={`${r.covered ? 'Covered' : 'No data'} ${r.start} to ${r.end}`}/>)}</div>{missing.map(r => <p key={r.start}>No data {r.start}–{r.end}. Excluded from daily averages.</p>)}<Row trailing={<span>{health.score === null ? 'No transactions' : `${health.score}/100`}</span>}>Data health</Row><p className="meta">Equal weight: coverage, categorised rows and matched transfers. {health.uncategorized} uncategorised · {health.unmatchedTransfers} unmatched transfers. This describes data completeness, not your financial wellbeing.</p></section>;
}
function FileReview({ id, accounts, onClose, onStaged }: { id: string; accounts: Account[]; onClose: () => void; onStaged: (id: string) => void }) {
  const session = useSession(), query = useQueryClient();
  const [accountId, setAccount] = useState(accounts[0]?.id ?? ''), [start, setStart] = useState(''), [end, setEnd] = useState(''), [opening, setOpening] = useState(''), [closing, setClosing] = useState(''), [dateOrder, setOrder] = useState<'DMY' | 'MDY'>('DMY'), [decimal, setDecimal] = useState<'.' | ','>('.'), [invert, setInvert] = useState(true), [payslip, setPayslip] = useState(false), [progress, setProgress] = useState(''), [headers, setHeaders] = useState<string[]>([]), [mapping, setMapping] = useState<Columns | undefined>();
  const selectedAccountId = accountId || accounts[0]?.id || '';
  const mutation = useMutation({ mutationFn: async () => {
    const account = accounts.find(a => a.id === selectedAccountId); if (!account) throw new Error('Choose the account this statement belongs to.');
    const context: ImportContext = { accountId: account.id, accountKind: account.type as ImportContext['accountKind'], currency: currency(account.currency), period: { start, end }, dateOrder, decimal, creditPositivePurchases: invert };
    const file = await session.run(repo => repo.imports.loadFile(id)), aliases = await session.run(repo => repo.imports.aliases()), bytes = decodeFile(file.data);
    try {
      const { extract } = await import('../../ingest/extract');
      const extracted = await extract(bytes, file.fileName, setProgress); if (extracted.table?.[0]) setHeaders(extracted.table[0]);
      const doc = buildDocument(extracted, file.hash, file.fileName, context, payslip ? '0' : opening, payslip ? '0' : closing, payslip, mapping, aliases);
      return await session.run(async repo => { const result = await repo.imports.stage(doc); await repo.imports.removeFile(id); return result; });
    } finally { bytes.fill(0); }
  }, onSuccess: async result => { await query.invalidateQueries({ queryKey: ['imports'] }); onStaged(result.id); } });
  const discard = useMutation({ mutationFn: () => session.run(repo => repo.imports.removeFile(id)), onSuccess: async () => { await query.invalidateQueries({ queryKey: ['imports'] }); onClose(); } });
  return <Sheet title="Confirm statement details" onClose={() => { if (!mutation.isPending && !discard.isPending) onClose(); }}><form className="stack" onSubmit={e => { e.preventDefault(); mutation.mutate(); }}><label className="input-label">Account<select value={selectedAccountId} onChange={e => setAccount(e.target.value)}>{accounts.map(a => <option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label><label className="check-row"><input type="checkbox" checked={payslip} onChange={e => setPayslip(e.target.checked)}/>This is a payslip</label><div className="split-field"><Input label="Statement start" type="date" required value={start} onChange={e => setStart(e.target.value)}/><Input label="Statement end" type="date" required value={end} onChange={e => setEnd(e.target.value)}/></div><p className="meta">Use the dates printed on this file. For payslips, include the pay date in this window.</p>
    {!payslip && <><Input label="Stated opening balance" required inputMode="decimal" value={opening} onChange={e => setOpening(e.target.value)}/><Input label="Stated closing balance" required inputMode="decimal" value={closing} onChange={e => setClosing(e.target.value)}/><p className="meta">For credit cards, enter money owed as negative balances.</p></>}
    <div className="split-field"><label className="input-label">Date format<select value={dateOrder} onChange={e => setOrder(e.target.value as 'DMY' | 'MDY')}><option value="DMY">Day / month</option><option value="MDY">Month / day</option></select></label><label className="input-label">Decimal separator<select value={decimal} onChange={e => setDecimal(e.target.value as '.' | ',')}><option value=".">Dot · 1,234.56</option><option value=",">Comma · 1.234,56</option></select></label></div>
    {accounts.find(a => a.id === selectedAccountId)?.type === 'credit' && <label className="check-row"><input type="checkbox" checked={invert} onChange={e => setInvert(e.target.checked)}/>Positive signed amounts are card purchases</label>}
    {headers.length > 0 && <details><summary>Map columns</summary><p>Choose a signed amount column, or both debit and credit columns.</p>{(['date', 'description', 'amount', 'debit', 'credit', 'reference'] as const).map(key => <label className="input-label" key={key}>{key === 'date' ? 'Date column' : key === 'description' ? 'Description column' : key === 'amount' ? 'Amount column' : key === 'debit' ? 'Debit column' : key === 'credit' ? 'Credit column' : 'Reference column'}<select value={mapping?.[key] ?? ''} onChange={e => setMapping(current => ({ ...(current ?? { date: -1, description: -1, amount: null, debit: null, credit: null, reference: null }), [key]: e.target.value === '' ? (key === 'date' || key === 'description' ? -1 : null) : Number(e.target.value) }))}><option value="">Automatic / not used</option>{headers.map((h, i) => <option key={i} value={i}>{h || `Column ${i + 1}`}</option>)}</select></label>)}</details>}
    {mutation.error && <Failure error={mutation.error}/>} {discard.error && <Failure error={discard.error}/>} {mutation.isPending && <p role="status">{progress || 'Reading file…'}</p>}<div className="form-actions"><Button disabled={mutation.isPending || discard.isPending} onClick={() => discard.mutate()}>Discard file</Button><Button type="submit" variant="primary" disabled={mutation.isPending || discard.isPending}>Extract for review</Button></div></form></Sheet>;
}
function BatchReview({ id, onClose }: { id: string; onClose: () => void }) {
  const session = useSession(), query = useQueryClient(); const [selected, setSelected] = useState<Review['items'][number] | null>(null), [page, setPage] = useState(0);
  const review = useQuery({ queryKey: ['import-review', id], queryFn: () => session.run(repo => repo.imports.review(id)) });
  const commit = useMutation({ mutationFn: () => session.run(repo => repo.imports.commit(id)), onSuccess: async () => { await query.invalidateQueries(); onClose(); } });
  const discard = useMutation({ mutationFn: () => session.run(repo => repo.imports.rollback(id)), onSuccess: async () => { await query.invalidateQueries(); onClose(); } });
  const value = review.data;
  return <Sheet title="Review import" onClose={() => { if (!commit.isPending && !discard.isPending) onClose(); }}><div className="stack">{review.error && <Failure error={review.error}/>} {value && <><p>{value.doc.fileName}</p>{value.doc.status === 'committed' ? <p>This file is already imported. No transactions were added a second time.</p> : <><div className="review-counts"><span>{value.newCount} new</span><span>{value.duplicateCount} duplicates skipped</span><span>{value.uncertainCount} uncertain</span></div><p>{value.balance.valid ? '✓ Balance check passed' : `Balance mismatch: ${format(money(value.balance.difference, value.doc.context.currency))}. This import is quarantined.`}</p><p>{coveredDays(value.coverageAdded)} new covered days. Coverage: {value.doc.context.period.start}–{value.doc.context.period.end}{value.doc.payslip ? ' · Payslips do not add statement coverage' : ''}</p>{!value.doc.payslip && <BalanceCorrection review={value}/>}{value.doc.payslip && <div className="stack"><h3>{value.doc.payslip.employer}</h3><p>Pay date {value.doc.payslip.payDate}</p>{(['gross', 'net', 'tax', 'super'] as const).map(key => <Row key={key} trailing={<Amount value={money(BigInt(value.doc.payslip![key]), value.doc.context.currency)} context={`Payslip ${key}`}/>}>{key === 'gross' ? 'Gross pay' : key === 'net' ? 'Net pay' : key === 'tax' ? 'Tax withheld' : 'Super / pension'}</Row>)}<PayslipCorrection review={value}/><p className="meta">Gross includes allowances. Deductions reduce net pay; employer super does not. Check these values against your source.</p></div>}
    {value.items.slice(page * 40, (page + 1) * 40).map(item => <button key={item.row.sourceId} type="button" className="transaction-row" onClick={() => setSelected(item)}><span><strong>{item.row.merchant}</strong><span className="meta">{item.row.date} · {item.blocked ? 'Review needed' : item.duplicate ? 'Duplicate' : item.row.category ?? 'Uncategorised'}</span></span><Amount value={money(BigInt(item.row.minor), item.row.currency)} context={item.row.merchant}/></button>)}{value.items.length > 40 && <div className="form-actions"><Button disabled={!page} onClick={() => setPage(p => p - 1)}>Previous rows</Button><Button disabled={(page + 1) * 40 >= value.items.length} onClick={() => setPage(p => p + 1)}>Next rows</Button></div>}
    {commit.error && <Failure error={commit.error}/>} {discard.error && <Failure error={discard.error}/>}<div className="form-actions"><Button disabled={commit.isPending || discard.isPending} onClick={() => discard.mutate()}>Discard import</Button><Button variant="primary" disabled={!value.balance.valid || value.uncertainCount > 0 || commit.isPending || discard.isPending} onClick={() => commit.mutate()}>{commit.isPending ? 'Committing…' : 'Confirm import'}</Button></div></>}</>}{selected && <RowCorrection id={id} item={selected} onClose={() => setSelected(null)}/>}</div></Sheet>;
}
function BalanceCorrection({ review }: { review: Review }) {
  const session = useSession(), query = useQueryClient(); const code = review.doc.context.currency;
  const [opening, setOpening] = useState(decimalString(review.doc.opening, code)), [closing, setClosing] = useState(decimalString(review.doc.closing, code));
  const update = useMutation({ mutationFn: () => session.run(repo => repo.imports.correctBalances(review.doc.id, normalizeAmount(opening, code, '.').toString(), normalizeAmount(closing, code, '.').toString())), onSuccess: () => query.invalidateQueries({ queryKey: ['import-review', review.doc.id] }) });
  return <details><summary>Check stated balances</summary><div className="stack"><Input label="Opening balance (decimal dot)" value={opening} onChange={e => setOpening(e.target.value)}/><Input label="Closing balance (decimal dot)" value={closing} onChange={e => setClosing(e.target.value)}/><p className="meta">Copy the values printed on the statement. Do not change them just to clear a mismatch.</p>{update.error && <Failure error={update.error}/>}<Button disabled={update.isPending} onClick={() => update.mutate()}>Save stated balances</Button></div></details>;
}
function RowCorrection({ id, item, onClose }: { id: string; item: Review['items'][number]; onClose: () => void }) {
  const session = useSession(), query = useQueryClient(); const row = item.row;
  const [date, setDate] = useState(row.date), [description, setDescription] = useState(row.description), [amount, setAmount] = useState(decimalString(row.minor, row.currency)), [category, setCategory] = useState(row.category ?? item.suggestion.category ?? ''), [rule, setRule] = useState(false), [distinct, setDistinct] = useState(!!row.occurrence), [duplicateOf, setDuplicate] = useState(row.duplicateOf ?? '');
  const correction = useMutation({ mutationFn: () => {
    const change: Pick<NormalizedRow, 'date' | 'description' | 'merchant' | 'minor' | 'category' | 'occurrence' | 'duplicateOf'> = { date, description, merchant: merchantName(description), minor: normalizeAmount(amount, row.currency, '.').toString(), category: category || null, occurrence: distinct ? row.reference || `${id}:${row.sourceId}` : '', duplicateOf: duplicateOf || null };
    return session.run(repo => repo.imports.correct(id, row.sourceId, change, rule));
  }, onSuccess: async () => { await query.invalidateQueries({ queryKey: ['import-review', id] }); onClose(); } });
  return <Sheet title="Check transaction" onClose={() => { if (!correction.isPending) onClose(); }}><form className="stack" onSubmit={e => { e.preventDefault(); correction.mutate(); }}><pre className="raw-excerpt">{item.original?.description ?? row.description}{'\n'}{item.original?.date ?? row.date} · {item.original?.amount ?? decimalString(row.minor, row.currency)} {row.currency}</pre>{row.issues.map(issue => <p key={issue}>{issue}</p>)}<p className="meta">{item.suggestion.reason}</p><Input label="Posted date" type="date" required value={date} onChange={e => setDate(e.target.value)}/><Input label="Description" required value={description} onChange={e => setDescription(e.target.value)}/><Input label="Signed amount (decimal dot)" required value={amount} onChange={e => setAmount(e.target.value)}/><label className="input-label">Category<select value={category} onChange={e => setCategory(e.target.value)}><option value="">Leave uncategorised</option>{categoryNames.map(c => <option key={c}>{c}</option>)}</select></label><label className="check-row"><input type="checkbox" checked={rule} onChange={e => setRule(e.target.checked)}/>Use this category for this merchant in future imports</label>{item.collision && <><p>Identical date, merchant and amount appear more than once. Confirm whether this is another purchase or the same transaction.</p><label className="check-row"><input type="checkbox" checked={distinct} onChange={e => setDistinct(e.target.checked)}/>Keep as a separate purchase</label></>}{item.near.length > 0 && <label className="input-label">Possible pending-to-posted duplicate<select value={duplicateOf} onChange={e => setDuplicate(e.target.value)}><option value="">Keep as a separate transaction</option>{item.near.filter(r => r.sources.some(s => s.batchId !== id)).map(r => <option key={r.id} value={r.id}>Same transaction as {r.date} · {r.merchant}</option>)}</select></label>}{correction.error && <Failure error={correction.error}/>}<Button variant="primary" type="submit" disabled={correction.isPending}>Confirm this row</Button></form></Sheet>;
}
function PayslipCorrection({ review }: { review: Review }) {
  const session = useSession(), query = useQueryClient(); const original = review.doc.payslip!;
  const [pay, setPay] = useState(original), [values, setValues] = useState({ gross: decimalString(original.gross, original.currency), net: decimalString(original.net, original.currency), tax: decimalString(original.tax, original.currency), super: decimalString(original.super, original.currency) });
  const update = useMutation({ mutationFn: () => session.run(repo => repo.imports.correctPayslip(review.doc.id, { ...pay, gross: normalizeAmount(values.gross, pay.currency, '.').toString(), net: normalizeAmount(values.net, pay.currency, '.').toString(), tax: normalizeAmount(values.tax, pay.currency, '.').toString(), super: normalizeAmount(values.super, pay.currency, '.').toString() })), onSuccess: () => query.invalidateQueries({ queryKey: ['import-review', review.doc.id] }) });
  return <details><summary>Check payslip fields and source</summary><div className="stack"><pre className="raw-excerpt">{review.doc.sourceText ?? 'Open the original payslip to compare these fields.'}</pre><Input label="Employer" value={pay.employer} onChange={e => setPay(p => ({ ...p, employer: e.target.value }))}/><Input label="Pay date" type="date" value={pay.payDate} onChange={e => setPay(p => ({ ...p, payDate: e.target.value }))}/><Input label="Pay period start" type="date" value={pay.period.start} onChange={e => setPay(p => ({ ...p, period: { ...p.period, start: e.target.value } }))}/><Input label="Pay period end" type="date" value={pay.period.end} onChange={e => setPay(p => ({ ...p, period: { ...p.period, end: e.target.value } }))}/>{(['gross', 'net', 'tax', 'super'] as const).map(key => <Input key={key} label={key === 'gross' ? 'Gross pay (decimal dot)' : key === 'net' ? 'Net pay (decimal dot)' : key === 'tax' ? 'Tax withheld (decimal dot)' : 'Super / pension (decimal dot)'} value={values[key]} onChange={e => setValues(v => ({ ...v, [key]: e.target.value }))}/>)}{original.allowances.map((a, i) => <Row key={`a${i}`} trailing={<Amount value={money(BigInt(a.minor), pay.currency)} context={a.name}/>}>Allowance · {a.name}</Row>)}{original.deductions.map((a, i) => <Row key={`d${i}`} trailing={<Amount value={money(BigInt(a.minor), pay.currency)} context={a.name}/>}>Deduction · {a.name}</Row>)}{Object.entries(original.ytd).map(([name, minor]) => <Row key={name} trailing={<Amount value={money(BigInt(minor), pay.currency)} context={`Year to date ${name}`}/>}>Year to date · {name}</Row>)}{update.error && <Failure error={update.error}/>}<Button disabled={update.isPending} onClick={() => update.mutate()}>Save payslip fields</Button></div></details>;
}
