import {AllocationBreakdown} from './AllocationBreakdown';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useSession} from '../session';
import {useDisplayCurrencyState} from '../currency';
import {Amount,Button,Input,Row,Sheet,Skeleton,Surface} from '../design/primitives';
import {SourceLine} from '../design/SourceLine';
import {DayStrip} from '../design/DayStrip';
import {AxisPositions} from '../design/AxisPositions';
import {currency,money,parseDecimal,format} from '../../core/money';
import {localDay} from '../../ingest/reminders';
import {day} from '../../intelligence/model';
import type {Transaction} from '../../intelligence/model';
import type {intelligenceRepository} from '../../ledger/intelligence';
type Report=Awaited<ReturnType<ReturnType<typeof intelligenceRepository>['analyse']>>;
export function Intelligence({mode='insights'}:{mode?:'insights'|'today'}){
 const session=useSession(),client=useQueryClient(),[detail,setDetail]=useState<{title:string;ids:string[];text:string}|null>(null),[edit,setEdit]=useState<Transaction|null>(null),[reflection,setReflection]=useState(false),[goal,setGoal]=useState(false),[scenario,setScenario]=useState(false),[extra,setExtra]=useState('0'),[cut,setCut]=useState('0'),[applied,setApplied]=useState({extra:'0',cut:0}),[error,setError]=useState('');
 // The analysis opened in Australian dollars for everybody, because 'AUD' was the initial state of a
 // picker. Someone whose money is in pesos got an empty screen and no clue why — and a picker of its own
 // meant this screen could disagree with every other one. There is one currency in this app now.
 const {code,settled}=useDisplayCurrencyState();
 const today=localDay();const q=useQuery({queryKey:['intelligence',today,code,applied],queryFn:()=>session.run(r=>r.intelligence.analyse(today,code,applied.extra,applied.cut)),enabled:session.state==='ready'&&settled,staleTime:0});
 const refresh=async()=>{await client.invalidateQueries({queryKey:['intelligence']});};
 const show=(title:string,ids:string[],text='')=>setDetail({title,ids,text});
 if(session.state==='preview')return <p>Intelligence reads your encrypted ledger in the Android app.</p>;
 if(q.isPending)return <Skeleton label="Reading money evidence"/>;
 if(q.error)return <p role="alert">The money evidence could not be read. Reopen Kairos and try again.</p>;
 const r=q.data!;const amount=(minor:string,context:string)=><Amount value={money(BigInt(minor),currency(code))} context={context}/>;
 const signal=r.signals.filter(v=>v.period.startsWith('trailing-90:')),f=r.forecast;
 const formatted=(v:string)=>format(money(BigInt(v),currency(code)));
 const forecastWorking=[...(f.status==='ok'?[`Available liquid balance ${formatted(r.snapshot.liquid!.minor)}, less pending purchases ${formatted(f.pending)}, outstanding credit ${formatted(r.snapshot.committedLiability?.minor??'0')}, bills before next pay ${formatted(f.committed)}, and chosen buffer ${formatted(f.buffer)}. Divide the remainder by ${day(f.nextPay!)-day(today)} days; amounts below zero are shown as zero.`]:[]),...f.assumptions].join(' ');
 const evidenceButton=(title:string,ids:string[],text:string,child:React.ReactNode)=><Button variant="quiet" onClick={()=>show(title,ids,text)}>{child}</Button>;
 return <section className="stack intelligence" aria-label="Money evidence">
 {r.distress?<Surface className="surface-muted"><h2>Focus on essentials</h2><p>Keep this small. The next essential bill, and the money available for it.</p><p>Free, confidential financial counselling: National Debt Helpline, <a href="tel:1800007007">1800 007 007</a>.</p>{evidenceButton('Triage evidence',r.profile.evidence,'Precautionary thresholds: buffer below 5 days, rising explicitly recorded high-interest debt, or repeated recorded overdraft fees. These are not a diagnosis.','View the evidence')}</Surface>:mode==='insights'&&<><h2>{r.profile.archetype??'Still learning'}</h2><p>{r.profile.reason}</p>{r.profile.movement&&<p>{r.profile.movement}. Patterns can change with the evidence.</p>}{evidenceButton('Profile evidence',r.profile.evidence,'Descriptive heuristic, not a clinical or validated personality assessment.',`${r.profile.coveredDays} covered days · ${r.profile.confidence}% evidence completeness`)}<AxisPositions axes={Object.entries(r.profile.axes).map(([key,v])=>({name:key,at:v}))}/>
 {evidenceButton('What these describe',r.profile.evidence,'Version 1 descriptive axes; missing inputs remain unknown. They describe recorded patterns, not a diagnosis or a score of financial worth.','See what these are based on')}</>}
 {mode==='insights'&&signal.some(v=>v.unverified)&&<p className="muted">Some statements had no closing balance to check against. Those figures are approximate.</p>}
 {r.insights.map(i=><Surface key={i.id}><h3>{i.title}</h3><p>{i.body}</p><p>{i.action}</p><Row trailing={evidenceButton(i.title,i.evidence,`${i.threshold}. ${i.assumption} Calculation: ${i.inputs.baseMinor} × ${i.inputs.numerator}/${i.inputs.denominator} minor units. Research: ${i.researchId}.`,amount(i.projectedMinor,'conditional scenario'))}>Conditional scenario</Row><p className="meta">{i.assumption}</p><Button onClick={()=>void session.run(repo=>repo.intelligence.dismiss(i.kind)).then(refresh).catch(()=>setError('Could not save the dismissal. Try again.'))}>Dismiss suggestion</Button></Surface>)}
 {mode==='today'&&<DayStrip today={today} code={currency(code)} days={r.snapshot.transactions.filter(t=>t.currency===currency(code)&&t.status==='settled'&&!t.transfer&&t.kind!=='transfer').map(t=>({date:t.date,minor:t.minor}))}/>}
 {!r.distress&&(f.status==='ok'||mode==='insights')&&<><h2>{mode==='today'?'Money you can spend':'Cashflow outlook'}</h2>{f.status==='ok'?<><Row trailing={evidenceButton('Safe-to-spend working',f.evidence,forecastWorking,amount(f.safeDaily!,'safe to spend per day'))}>Safe to spend per day</Row><p className="meta">Until next expected pay: {f.nextPay}. Future pay is not available money today.</p>{f.horizons.map(h=><Row key={h.days} trailing={evidenceButton('Forecast assumptions',f.evidence,forecastWorking,<span>{amount(h.low,'lower scenario')} – {amount(h.high,'upper scenario')}</span>)}>{h.days}-day range</Row>)}<Button onClick={()=>show('Forecast assumptions',f.evidence,forecastWorking)}>See assumptions and sources</Button></>:<p>{f.reason}</p>}
 {mode==='insights'&&<div className="form-actions"><Button onClick={()=>setScenario(true)}>Spending scenario</Button><Button onClick={()=>setGoal(true)}>Money set aside</Button></div>}
 {mode==='insights'&&<><Button onClick={()=>setReflection(true)}>Optional reflections</Button>
<h2>Goals</h2>{!r.goals.length&&<p>No goals yet. Name the future expense you want to reserve money for.</p>}{r.goals.map(g=><Row key={String(g.id)} trailing={evidenceButton('Goal funding',[],`Target ${g.target_minor}, funded ${g.funded_minor} minor units, due ${g.target_date}. User-entered plan; not an imported transaction.`,g.perPay===null?'Pay cycle needed':amount(g.perPay,'per pay allocation'))}>{String(g.name)}<p className="meta">{String(g.kind)} · {String(g.target_date)}</p></Row>)}{r.payRise.map(p=><Surface key={p.employer}><h3>A sustained pay increase</h3><p>{p.action}</p><p>{p.assumption}</p>{evidenceButton('Pay-rise evidence',r.snapshot.pays.filter(x=>p.evidence.includes(x.id)).flatMap(x=>x.transactionId?[x.transactionId]:[]),JSON.stringify(p),amount(p.suggested,'half of observed increase per pay'))}</Surface>)}</>}
 </>}
 {error&&<p role="alert">{error}</p>}
 {detail&&<Sheet title={detail.title} onClose={()=>setDetail(null)}><p>{detail.text}</p>{r.snapshot.transactions.filter(t=>detail.ids.includes(t.id)).map(t=><div className="section-gap" key={t.id}><Row trailing={amount(t.minor,t.description)}><h3>{t.description}</h3><p>{t.date} · {t.category} · {t.status}</p></Row><AllocationBreakdown parts={t.allocations} code={t.currency}/>{t.sources?.map((s,i)=><SourceLine key={i} file={s.file} row={s.row} raw={s.raw}/>)}<Button onClick={()=>{setEdit(t);setDetail(null);}}>Confirm purchase context</Button></div>)}{!detail.ids.length&&<p>This value is a plan or assumption, not an imported transaction.</p>}</Sheet>}
 {reflection&&<ReflectionSheet onClose={()=>setReflection(false)} saved={refresh}/>}
 {edit&&<ContextSheet row={edit} onClose={()=>setEdit(null)} saved={refresh}/>}
 {goal&&<GoalSheet report={r} code={code} onClose={()=>setGoal(false)} saved={refresh}/>}
 {scenario&&<Sheet title="Spending scenario" onClose={()=>setScenario(false)}><p>Nothing here is saved to your ledger.</p><Input label="A new cost to take on" inputMode="decimal" value={extra} onChange={e=>setExtra(e.target.value)} hint="A one-off amount you are thinking of committing to."/><Input label="Cut my day-to-day spending by (%)" type="number" min="0" max="100" value={cut} onChange={e=>setCut(e.target.value)} hint="Applies to spending left after bills and other commitments."/><Button onClick={()=>{try{const n=Number(cut);if(!Number.isInteger(n)||n<0||n>100)throw new Error('Use a whole percent from 0 to 100.');const x=parseDecimal(extra,currency(code));if(x.minor<0n)throw new Error('Use a non-negative commitment.');setApplied({extra:x.minor.toString(),cut:n});setScenario(false);setError('');}catch(e){setError(e instanceof Error?e.message:'Check the scenario.');}}}>Apply scenario</Button><Button onClick={()=>{setApplied({extra:'0',cut:0});setScenario(false);}}>Reset scenario</Button></Sheet>}
 </section>;
}
function GoalSheet({report,code,onClose,saved}:{report:Report;code:string;onClose:()=>void;saved:()=>Promise<void>}){
 const session=useSession(),[name,setName]=useState(''),[target,setTarget]=useState(''),[funded,setFunded]=useState('0'),[date,setDate]=useState(''),[kind,setKind]=useState<'goal'|'sinking'|'budget'>('goal'),[buffer,setBuffer]=useState(''),[error,setError]=useState('');
 return <Sheet title="Money set aside" onClose={onClose}><p>Labels on money you already have. Naming it does not move it.</p><p>Currently kept untouched: <Amount value={money(BigInt(report.buffer),currency(code))} context="chosen buffer"/>.</p><Input label="Keep this much untouched" value={buffer} inputMode="decimal" onChange={e=>setBuffer(e.target.value)} hint="Your cushion for the unexpected. It is left out of what the app says you can spend."/><Button onClick={()=>void session.run(r=>r.intelligence.setBuffer(code,parseDecimal(buffer,currency(code)).minor.toString())).then(saved).catch(e=>setError(String(e)))}>Save the amount to keep untouched</Button><Input label="What are you saving for?" value={name} onChange={e=>setName(e.target.value)} hint="A holiday, a car repair, anything with a cost you know is coming."/><Input label="Target amount" value={target} inputMode="decimal" onChange={e=>setTarget(e.target.value)}/><Input label="Already put aside for it" value={funded} inputMode="decimal" onChange={e=>setFunded(e.target.value)}/><Input label="Target date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><label className="input-label">Plan type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="goal">Goal</option><option value="sinking">Sinking fund</option><option value="budget">Budget</option></select></label><Button onClick={()=>void session.run(r=>r.intelligence.saveGoal({id:crypto.randomUUID(),name,target:parseDecimal(target,currency(code)).minor.toString(),funded:parseDecimal(funded,currency(code)).minor.toString(),date,kind,currency:code})).then(saved).then(onClose).catch(e=>setError(String(e)))}>Save goal</Button>{error&&<p role="alert">{error}</p>}</Sheet>;
}
function ContextSheet({row,onClose,saved}:{row:Transaction;onClose:()=>void;saved:()=>Promise<void>}){const session=useSession(),[instrument,setInstrument]=useState(row.instrument??''),[hour,setHour]=useState(row.hour===undefined?'':String(row.hour)),[error,setError]=useState('');return <Sheet title="Confirm purchase context" onClose={onClose}><p>Only what you know. Blank stays unknown.</p><label className="input-label">Payment instrument<select value={instrument} onChange={e=>setInstrument(e.target.value)}><option value="">Unknown</option>{['card','bnpl','cash','transfer'].map(x=><option key={x}>{x}</option>)}</select></label><Input label="Purchase-local hour" type="number" min="0" max="23" value={hour} onChange={e=>setHour(e.target.value)}/><Button onClick={()=>void session.run(r=>r.intelligence.annotate(row.id,{...(instrument?{instrument:instrument as NonNullable<Transaction['instrument']>}:{}),...(hour!==''?{hour:Number(hour)}:{})})).then(saved).then(onClose).catch(e=>setError(String(e)))}>Save context</Button>{error&&<p role="alert">{error}</p>}</Sheet>;}

function ReflectionSheet({onClose,saved}:{onClose:()=>void;saved:()=>Promise<void>}){const session=useSession(),[scores,setScores]=useState({planning:'',adherence:'',enjoyment:'',awareness:''}),[error,setError]=useState('');const labels={planning:'How far ahead do you plan spending?',adherence:'How consistently do you follow your own plan?',enjoyment:'How much enjoyment did your chosen spending bring?',awareness:'How aware are you of recurring commitments?'};return <Sheet title="Optional reflections" onClose={onClose}><p>Your own observations, not a psychological test. 0 is very little, 100 a great deal.</p>{(Object.keys(scores) as (keyof typeof scores)[]).map(k=><Input key={k} label={labels[k]} type="number" min="0" max="100" value={scores[k]} onChange={e=>setScores({...scores,[k]:e.target.value})}/>)}<Button onClick={()=>{if(Object.values(scores).some(v=>v==='')){setError('Complete all four reflections, or leave them unknown.');return;}void session.run(r=>r.intelligence.setReflection({planning:Number(scores.planning),adherence:Number(scores.adherence),enjoyment:Number(scores.enjoyment),awareness:Number(scores.awareness)})).then(saved).then(onClose).catch(e=>setError(String(e)));}}>Save reflections</Button><Button onClick={()=>void session.run(r=>r.intelligence.setReflection(null)).then(saved).then(onClose).catch(e=>setError(String(e)))}>Keep these unknown</Button>{error&&<p role="alert">{error}</p>}</Sheet>;}
