import {AllocationBreakdown} from './AllocationBreakdown';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useSession} from '../session';
import {Amount,Button,Input,Row,Sheet,Skeleton,Surface} from '../design/primitives';
import {currency,money,parseDecimal,format} from '../../core/money';
import {localDay} from '../../ingest/reminders';
import {day} from '../../intelligence/model';
import type {Transaction,Signal} from '../../intelligence/model';
import type {intelligenceRepository} from '../../ledger/intelligence';
type Report=Awaited<ReturnType<ReturnType<typeof intelligenceRepository>['analyse']>>;
const labels:Record<Signal['key'],string>={buffer_days:'Buffer days',impulse_ratio:'Unplanned spending proxy',payday_decay:'Payday spending ratio',spend_volatility:'Daily spending variability',category_concentration:'Category concentration',subscription_drag:'Recurring share of income',fixed_burden:'Essential and debt share',savings_consistency:'Months with positive savings',friction_profile:'Recorded card and BNPL share',late_night_share:'Late-night discretionary share',small_leak_index:'Small-purchase index',recovery_lag:'Recovery lag'};
function value(v:Signal){if(v.status!=='ok')return 'Not enough evidence';const x=BigInt(v.value!);if(v.unit.includes('basis points'))return `${x/100n}.${(x%100n).toString().padStart(2,'0')}%`;if(v.key==='buffer_days')return `${x/10000n}.${(x%10000n/1000n)} days`;return `${v.value} ${v.unit}`;}
export function Intelligence({mode='insights'}:{mode?:'insights'|'today'}){
 const session=useSession(),client=useQueryClient(),[code,setCode]=useState('AUD'),[detail,setDetail]=useState<{title:string;ids:string[];text:string}|null>(null),[edit,setEdit]=useState<Transaction|null>(null),[reflection,setReflection]=useState(false),[goal,setGoal]=useState(false),[scenario,setScenario]=useState(false),[extra,setExtra]=useState('0'),[cut,setCut]=useState('0'),[applied,setApplied]=useState({extra:'0',cut:0}),[error,setError]=useState('');
 const today=localDay();const q=useQuery({queryKey:['intelligence',today,code,applied],queryFn:()=>session.run(r=>r.intelligence.analyse(today,code,applied.extra,applied.cut)),enabled:session.state==='ready',staleTime:0});
 const refresh=async()=>{await client.invalidateQueries({queryKey:['intelligence']});};
 const show=(title:string,ids:string[],text='')=>setDetail({title,ids,text});
 if(session.state==='preview')return <p>Intelligence reads your encrypted ledger in the Android app.</p>;
 if(q.isPending)return <Skeleton label="Reading money evidence"/>;
 if(q.error)return <p role="alert">The money evidence could not be read. Reopen Kairos and try again.</p>;
 const r=q.data!;const amount=(minor:string,context:string)=><Amount value={money(BigInt(minor),currency(code))} context={context}/>;
 const signal=r.signals.filter(v=>v.period.startsWith('trailing-90:')),f=r.forecast;
 const formatted=(v:string)=>format(money(BigInt(v),currency(code)));
 const forecastWorking=[...(f.status==='ok'?[`Available liquid balance ${formatted(r.snapshot.liquid!.minor)}, less pending purchases ${formatted(f.pending)}, outstanding credit ${formatted(r.snapshot.committedLiability?.minor??'0')}, bills before next pay ${formatted(f.committed)}, and chosen buffer ${formatted(f.buffer)}. Divide the remainder by ${day(f.nextPay!)-day(today)} days; amounts below zero are shown as zero.`]:[]),...f.assumptions].join(' ');
 const evidenceButton=(title:string,ids:string[],text:string,child:React.ReactNode)=><Button variant="quiet" onClick={()=>show(title,ids,text)}>{child}</Button>;
 return <section className="stack intelligence" aria-label="Money evidence">
 {mode==='insights'&&<label className="input-label">Analysis currency<select value={code} onChange={e=>setCode(e.target.value)}>{['AUD','USD','PHP','EUR','GBP','NZD','CAD','SGD','JPY','KWD'].map(c=><option key={c}>{c}</option>)}</select></label>}
 {r.distress?<Surface className="surface-muted"><h2>Focus on essentials</h2><p>Keep this plan small. Check the next essential bill and the money available for it.</p><p>Free, confidential financial counselling: National Debt Helpline, <a href="tel:1800007007">1800 007 007</a>.</p>{evidenceButton('Triage evidence',r.profile.evidence,'Precautionary thresholds: buffer below 5 days, rising explicitly recorded high-interest debt, or repeated recorded overdraft fees. These are not a diagnosis.','View the evidence')}</Surface>:mode==='insights'&&<><h2>{r.profile.archetype??'Still learning'}</h2><p>{r.profile.reason}</p>{r.profile.movement&&<p>{r.profile.movement}. Patterns can change with the evidence.</p>}{evidenceButton('Profile evidence',r.profile.evidence,'Descriptive heuristic, not a clinical or validated personality assessment.',`${r.profile.coveredDays} covered days · ${r.profile.confidence}% evidence completeness`)}{Object.entries(r.profile.axes).map(([key,v])=><Row key={key} trailing={evidenceButton(key,r.profile.evidence,'Version 1 descriptive axis; missing inputs remain unknown.',v===null?'Unknown':`${Math.round(v)}/100`)}>{key}</Row>)}</>}
 {mode==='insights'&&signal.some(v=>v.unverified)&&<p className="muted">Some of this comes from statements that had no closing balance to check against, so treat those figures as approximate.</p>}
 {r.insights.map(i=><Surface key={i.id}><h3>{i.title}</h3><p>{i.body}</p><p>{i.action}</p><Row trailing={evidenceButton(i.title,i.evidence,`${i.threshold}. ${i.assumption} Calculation: ${i.inputs.baseMinor} × ${i.inputs.numerator}/${i.inputs.denominator} minor units. Research: ${i.researchId}.`,amount(i.projectedMinor,'conditional scenario'))}>Conditional scenario</Row><p className="meta">{i.assumption}</p><Button onClick={()=>void session.run(repo=>repo.intelligence.dismiss(i.kind)).then(refresh).catch(()=>setError('Could not save the dismissal. Try again.'))}>Dismiss suggestion</Button></Surface>)}
 {!r.distress&&(f.status==='ok'||mode==='insights')&&<><h2>{mode==='today'?'Money you can spend':'Cashflow outlook'}</h2>{f.status==='ok'?<><Row trailing={evidenceButton('Safe-to-spend working',f.evidence,forecastWorking,amount(f.safeDaily!,'safe to spend per day'))}>Safe to spend per day</Row><p className="meta">Until next expected pay: {f.nextPay}. Future pay is not available money today.</p>{f.horizons.map(h=><Row key={h.days} trailing={evidenceButton('Forecast assumptions',f.evidence,forecastWorking,<span>{amount(h.low,'lower scenario')} – {amount(h.high,'upper scenario')}</span>)}>{h.days}-day range</Row>)}<Button onClick={()=>show('Forecast assumptions',f.evidence,forecastWorking)}>See assumptions and sources</Button></>:<p>{f.reason}</p>}
 {mode==='insights'&&<div className="form-actions"><Button onClick={()=>setScenario(true)}>See what changes if I spend differently</Button><Button onClick={()=>setGoal(true)}>Money set aside</Button></div>}
 {mode==='insights'&&<><Button onClick={()=>setReflection(true)}>Optional reflections</Button><h2>Observed signals</h2>{r.signals.map(v=><Row key={v.period+v.key} trailing={evidenceButton(labels[v.key],v.evidence,`${v.reason} Window ${v.inputs.window.start} to ${v.inputs.window.end}. Covered days: ${v.inputs.coveredDays}. ${v.unverified?'Balance unverified.':''} ${JSON.stringify(v.details)}`,value(v))}><span>{labels[v.key]}</span><p className="meta">{v.period.startsWith('trailing')?'Trailing 90 days':v.period}</p></Row>)}<h2>Goals</h2>{!r.goals.length&&<p>No goals yet. Name the future expense you want to reserve money for.</p>}{r.goals.map(g=><Row key={String(g.id)} trailing={evidenceButton('Goal funding',[],`Target ${g.target_minor}, funded ${g.funded_minor} minor units, due ${g.target_date}. User-entered plan; not an imported transaction.`,g.perPay===null?'Pay cycle needed':amount(g.perPay,'per pay allocation'))}>{String(g.name)}<p className="meta">{String(g.kind)} · {String(g.target_date)}</p></Row>)}{r.payRise.map(p=><Surface key={p.employer}><h3>A sustained pay increase</h3><p>{p.action}</p><p>{p.assumption}</p>{evidenceButton('Pay-rise evidence',r.snapshot.pays.filter(x=>p.evidence.includes(x.id)).flatMap(x=>x.transactionId?[x.transactionId]:[]),JSON.stringify(p),amount(p.suggested,'half of observed increase per pay'))}</Surface>)}</>}
 </>}
 {error&&<p role="alert">{error}</p>}
 {detail&&<Sheet title={detail.title} onClose={()=>setDetail(null)}><p>{detail.text}</p>{r.snapshot.transactions.filter(t=>detail.ids.includes(t.id)).map(t=><div className="section-gap" key={t.id}><Row trailing={amount(t.minor,t.description)}><h3>{t.description}</h3><p>{t.date} · {t.category} · {t.status}</p></Row><AllocationBreakdown parts={t.allocations} code={t.currency}/>{t.sources?.map((s,i)=><details key={i}><summary>{s.file} · row {s.row}</summary><pre className="raw-excerpt">{s.raw}</pre></details>)}<Button onClick={()=>{setEdit(t);setDetail(null);}}>Confirm purchase context</Button></div>)}{!detail.ids.length&&<p>This value is a plan or assumption, not an imported transaction.</p>}</Sheet>}
 {reflection&&<ReflectionSheet onClose={()=>setReflection(false)} saved={refresh}/>}
 {edit&&<ContextSheet row={edit} onClose={()=>setEdit(null)} saved={refresh}/>}
 {goal&&<GoalSheet report={r} code={code} onClose={()=>setGoal(false)} saved={refresh}/>}
 {scenario&&<Sheet title="See what changes if I spend differently" onClose={()=>setScenario(false)}><p>Try a change and see what it would do to the figures above. Nothing here is saved to your ledger.</p><Input label="A new cost to take on" inputMode="decimal" value={extra} onChange={e=>setExtra(e.target.value)} hint="A one-off amount you are thinking of committing to."/><Input label="Cut my day-to-day spending by (%)" type="number" min="0" max="100" value={cut} onChange={e=>setCut(e.target.value)} hint="Applies to spending left after bills and other commitments."/><Button onClick={()=>{try{const n=Number(cut);if(!Number.isInteger(n)||n<0||n>100)throw new Error('Use a whole percent from 0 to 100.');const x=parseDecimal(extra,currency(code));if(x.minor<0n)throw new Error('Use a non-negative commitment.');setApplied({extra:x.minor.toString(),cut:n});setScenario(false);setError('');}catch(e){setError(e instanceof Error?e.message:'Check the scenario.');}}}>Apply scenario</Button><Button onClick={()=>{setApplied({extra:'0',cut:0});setScenario(false);}}>Reset scenario</Button></Sheet>}
 </section>;
}
function GoalSheet({report,code,onClose,saved}:{report:Report;code:string;onClose:()=>void;saved:()=>Promise<void>}){
 const session=useSession(),[name,setName]=useState(''),[target,setTarget]=useState(''),[funded,setFunded]=useState('0'),[date,setDate]=useState(''),[kind,setKind]=useState<'goal'|'sinking'|'budget'>('goal'),[buffer,setBuffer]=useState(''),[error,setError]=useState('');
 return <Sheet title="Money set aside" onClose={onClose}><p>Two things you can name here: an amount you want to keep untouched, and anything you are saving towards. Both are labels on money you already have — they do not move it, and they are not extra balances.</p><p>Currently kept untouched: <Amount value={money(BigInt(report.buffer),currency(code))} context="chosen buffer"/>.</p><Input label="Keep this much untouched" value={buffer} inputMode="decimal" onChange={e=>setBuffer(e.target.value)} hint="Your cushion for the unexpected. It is left out of what the app says you can spend."/><Button onClick={()=>void session.run(r=>r.intelligence.setBuffer(code,parseDecimal(buffer,currency(code)).minor.toString())).then(saved).catch(e=>setError(String(e)))}>Save the amount to keep untouched</Button><Input label="What are you saving for?" value={name} onChange={e=>setName(e.target.value)} hint="A holiday, a car repair, anything with a cost you know is coming."/><Input label="Target amount" value={target} inputMode="decimal" onChange={e=>setTarget(e.target.value)}/><Input label="Already put aside for it" value={funded} inputMode="decimal" onChange={e=>setFunded(e.target.value)}/><Input label="Target date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><label className="input-label">Plan type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="goal">Goal</option><option value="sinking">Sinking fund</option><option value="budget">Budget</option></select></label><Button onClick={()=>void session.run(r=>r.intelligence.saveGoal({id:crypto.randomUUID(),name,target:parseDecimal(target,currency(code)).minor.toString(),funded:parseDecimal(funded,currency(code)).minor.toString(),date,kind,currency:code})).then(saved).then(onClose).catch(e=>setError(String(e)))}>Save goal</Button>{error&&<p role="alert">{error}</p>}</Sheet>;
}
function ContextSheet({row,onClose,saved}:{row:Transaction;onClose:()=>void;saved:()=>Promise<void>}){const session=useSession(),[instrument,setInstrument]=useState(row.instrument??''),[hour,setHour]=useState(row.hour===undefined?'':String(row.hour)),[error,setError]=useState('');return <Sheet title="Confirm purchase context" onClose={onClose}><p>Only enter what you know. Leaving a field blank keeps it unknown.</p><label className="input-label">Payment instrument<select value={instrument} onChange={e=>setInstrument(e.target.value)}><option value="">Unknown</option>{['card','bnpl','cash','transfer'].map(x=><option key={x}>{x}</option>)}</select></label><Input label="Purchase-local hour" type="number" min="0" max="23" value={hour} onChange={e=>setHour(e.target.value)}/><Button onClick={()=>void session.run(r=>r.intelligence.annotate(row.id,{...(instrument?{instrument:instrument as NonNullable<Transaction['instrument']>}:{}),...(hour!==''?{hour:Number(hour)}:{})})).then(saved).then(onClose).catch(e=>setError(String(e)))}>Save context</Button>{error&&<p role="alert">{error}</p>}</Sheet>;}

function ReflectionSheet({onClose,saved}:{onClose:()=>void;saved:()=>Promise<void>}){const session=useSession(),[scores,setScores]=useState({planning:'',adherence:'',enjoyment:'',awareness:''}),[error,setError]=useState('');const labels={planning:'How far ahead do you plan spending?',adherence:'How consistently do you follow your own plan?',enjoyment:'How much enjoyment did your chosen spending bring?',awareness:'How aware are you of recurring commitments?'};return <Sheet title="Optional reflections" onClose={onClose}><p>These are your own observations, not a psychological test. Use 0 for very little and 100 for a great deal. Skip this to keep those profile inputs unknown.</p>{(Object.keys(scores) as (keyof typeof scores)[]).map(k=><Input key={k} label={labels[k]} type="number" min="0" max="100" value={scores[k]} onChange={e=>setScores({...scores,[k]:e.target.value})}/>)}<Button onClick={()=>{if(Object.values(scores).some(v=>v==='')){setError('Complete all four reflections, or leave them unknown.');return;}void session.run(r=>r.intelligence.setReflection({planning:Number(scores.planning),adherence:Number(scores.adherence),enjoyment:Number(scores.enjoyment),awareness:Number(scores.awareness)})).then(saved).then(onClose).catch(e=>setError(String(e)));}}>Save reflections</Button><Button onClick={()=>void session.run(r=>r.intelligence.setReflection(null)).then(saved).then(onClose).catch(e=>setError(String(e)))}>Keep these unknown</Button>{error&&<p role="alert">{error}</p>}</Sheet>;}
