import {hash} from '../../ingest/normalize';
import {TransactionAttachments} from './TransactionAttachments';
import {lazy,Suspense,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import type {Account} from '../../core/db/repository';
import type {ManualEntry} from '../../ledger/manual';
import {currency,money,parseDecimal} from '../../core/money';
import {localDay} from '../../ingest/reminders';
import {useSession} from '../session';
import {Amount,Button,Input,Row,Sheet} from '../design/primitives';
const TransactionSplits=lazy(()=>import('./TransactionSplits').then(m=>({default:m.TransactionSplits})));
const categories=['Groceries','Housing','Utilities','Transport','Health','Eating out','Shopping','Entertainment','Debt','Savings'];
export function ManualSheet({accounts,entry,onClose}:{accounts:Account[];entry?:ManualEntry;onClose:()=>void}){
 const session=useSession(),query=useQueryClient();
 const [id]=useState(entry?.id??crypto.randomUUID()),[kind,setKind]=useState<ManualEntry['kind']>(entry?.kind??'expense'),[accountId,setAccount]=useState(entry?.accountId??accounts[0]?.id??''),[destinationId,setDestination]=useState(entry?.destinationId??''),[date,setDate]=useState(entry?.date??localDay()),[amount,setAmount]=useState(()=>{if(!entry)return '';const a=accounts.find(a=>a.id===entry.accountId);const digits=new Intl.NumberFormat('en',{style:'currency',currency:a?.currency??'AUD'}).resolvedOptions().maximumFractionDigits??2;const n=BigInt(entry.minor),base=10n**BigInt(digits);return `${n/base}${digits?'.'+(n%base).toString().padStart(digits,'0'):''}`;}),[description,setDescription]=useState(entry?.description??''),[category,setCategory]=useState(entry?.category??''),[notes,setNotes]=useState(entry?.notes??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){setBusy(true);setError('');try{const account=accounts.find(a=>a.id===accountId);if(!account)throw new Error('Choose an account first.');await session.run(r=>r.manual.save({id,kind,accountId,destinationId:kind==='transfer'?destinationId:null,date,minor:parseDecimal(amount,currency(account.currency)).minor.toString(),description,category:category||null,notes}));await query.invalidateQueries();onClose();}catch(e){setError(e instanceof Error?e.message:'The entry could not be saved.');}finally{setBusy(false);}}
 return <Sheet title={entry?'Edit transaction':'Add transaction'} onClose={()=>{if(!busy)onClose();}}><form className="stack" onSubmit={e=>{e.preventDefault();void save();}}>
 <label className="input-label">Transaction type<select value={kind} onChange={e=>setKind(e.target.value as ManualEntry['kind'])}><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option></select></label>
 <label className="input-label">{kind==='transfer'?'From account':'Account'}<select value={accountId} onChange={e=>setAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label>
 {kind==='transfer'&&<label className="input-label">To account<select required value={destinationId} onChange={e=>setDestination(e.target.value)}><option value="">Choose account</option>{accounts.filter(a=>a.id!==accountId&&a.currency===accounts.find(b=>b.id===accountId)?.currency).map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label>}
 <Input label="Amount" inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)}/><Input label="Date" type="date" required value={date} onChange={e=>setDate(e.target.value)}/><Input label="Description" required maxLength={200} value={description} onChange={e=>setDescription(e.target.value)}/>
 {kind==='expense'&&<label className="input-label">Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Uncategorised</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label>}
 <Input label="Note (optional)" maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/><p className="meta">Saved on this device. Manual entries do not establish statement coverage or a verified balance.</p>{error&&<p role="alert">{error}</p>}<Button type="submit" variant="primary" disabled={busy||!accounts.length}>{busy?'Saving…':'Save transaction'}</Button></form></Sheet>;
}
export function ManualHistory({accounts,today=false}:{accounts:Account[];today?:boolean}){
 const session=useSession(),query=useQueryClient(),[edit,setEdit]=useState<ManualEntry>(),[remove,setRemove]=useState<ManualEntry>(),[match,setMatch]=useState<ManualEntry>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const data=useQuery({queryKey:['manual'],queryFn:()=>session.run(async r=>({entries:await r.manual.list(),totals:await r.manual.today(localDay()),unresolved:await r.manual.unresolved()})),enabled:session.state==='ready'});
 const candidates=useQuery({queryKey:['manual-matches',match?.id],queryFn:()=>session.run(r=>r.manual.candidates(match!.id)),enabled:!!match&&session.state==='ready'});
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await query.invalidateQueries();setRemove(undefined);setMatch(undefined);}catch(e){setError(e instanceof Error?e.message:'The change could not be saved.');}finally{setBusy(false);}}
 if(today)return <section className="section-gap"><h2>Recorded today</h2>{data.data&&Object.keys(data.data.unresolved).length>0&&<p>Possible duplicate entries need review in Ledger. These totals may count the same transaction twice.</p>}{data.error&&<p role="alert">Today's entries could not be read.</p>}{data.data?.totals.map(t=><div key={t.currency}><Row trailing={<Amount value={money(BigInt(t.spending),currency(t.currency))} context="recorded spending today"/>}>Spent</Row><Row trailing={<Amount value={money(BigInt(t.income),currency(t.currency))} context="recorded income today"/>}>Received</Row></div>)}{data.data&&!data.data.totals.length&&<p>No income or spending recorded today.</p>}<p className="meta">Recorded transactions only. Transfers are excluded.</p></section>;
 return <section className="section-gap"><h2>Manual transactions</h2>{data.error&&<p role="alert">Manual history could not be read. Try reopening Ledger.</p>}{data.data?.entries.slice().sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id)).map(e=>{const account=accounts.find(a=>a.id===e.accountId);return <div key={e.id} className="section-gap"><Row trailing={account&&<Amount value={money(BigInt(e.minor)*(e.kind==='expense'?-1n:1n),currency(account.currency))} context={`${e.kind} ${e.description}`}/>}><h3>{e.description}</h3><p>{e.date} · {account?.name} · {e.kind}</p></Row>{data.data?.unresolved[e.id]&&<p role="status">{data.data.unresolved[e.id]} possible statement matches. Review before trusting combined totals.</p>}{e.notes&&<p>{e.notes}</p>}<ReceiptDetails id={e.id}/>{e.kind==='expense'&&account&&Object.keys(e.links).length===0&&<ManualSplit id={e.id} minor={e.minor} code={account.currency}/>}<div className="form-actions"><Button onClick={()=>setEdit(e)}>Edit</Button><Button onClick={()=>setMatch(e)}>Match with statement</Button><Button onClick={()=>setRemove(e)}>Delete</Button></div>{Object.keys(e.links).length>0&&<p className="meta">A statement match is saved. If that source is rolled back, the manual entry counts again.</p>}</div>;})}
 {edit&&<ManualSheet accounts={accounts} entry={edit} onClose={()=>setEdit(undefined)}/>}
 {remove&&<Sheet title="Delete manual transaction?" onClose={()=>{if(!busy)setRemove(undefined);}}><p>{remove.description}. This removes the manual record only; imported statement entries remain.</p><Button variant="danger" disabled={busy} onClick={()=>void act(()=>session.run(r=>r.manual.remove(remove.id)))}>Delete transaction</Button>{error&&<p role="alert">{error}</p>}</Sheet>}
 {match&&<Sheet title="Match with statement" onClose={()=>{if(!busy)setMatch(undefined);}}><p>Confirm only if these are the same purchase or transfer. Similar amounts can be different transactions.</p>{candidates.data?.map(c=><Row key={c.leg+c.batchId+c.sourceId} trailing={<Button disabled={busy} onClick={()=>void act(()=>session.run(r=>r.manual.match(match.id,c.leg,c.transactionId)))}>Same transaction</Button>}>{c.description}<p>{c.date} · {c.leg==='entry'?'Statement transaction':c.leg==='from'?'Transfer out':'Transfer in'}</p></Row>)}{candidates.data&&!candidates.data.length&&<p>No imported entry with the same account and amount within three days. Import the statement first, or keep these separate.</p>}{Object.keys(match.links).length>0&&<Button disabled={busy} onClick={()=>void act(()=>session.run(r=>r.manual.unmatch(match.id)))}>Remove saved matches</Button>}{(error||candidates.error)&&<p role="alert">{error||'Matches could not be read.'}</p>}</Sheet>}
 </section>;
}
function ReceiptDetails({id}:{id:string}){const [open,setOpen]=useState(false);return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Notes and receipts</summary>{open&&<TransactionAttachments target={'manual:'+id}/>}</details>;}

function ManualSplit({id,minor,code}:{id:string;minor:string;code:string}){const [open,setOpen]=useState(false);return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Split expense categories</summary>{open&&<Suspense fallback={<p>Opening category split…</p>}><TransactionSplits id={hash('manual-transaction:'+id+':entry')} minor={(-BigInt(minor)).toString()} code={currency(code)}/></Suspense>}</details>;}
