import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {currency,currencyDigits,money,parseDecimal} from '../../core/money';
import {netWorthHistory} from '../../ledger/net-worth';
import {displayRatio} from '../../intelligence/visuals';
import {localDay} from '../../ingest/reminders';
import {Amount,Button,Input,Row,Sheet} from '../design/primitives';
import {useSession} from '../session';
export function NetWorth(){
 const session=useSession(),client=useQueryClient(),[open,setOpen]=useState(false),[item,setItem]=useState(''),[name,setName]=useState(''),[code,setCode]=useState('AUD'),[kind,setKind]=useState<'asset'|'liability'>('asset'),[date,setDate]=useState(localDay()),[amount,setAmount]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState<string|null>(null);
 const q=useQuery({queryKey:['net-worth'],enabled:session.state==='ready',queryFn:()=>session.run(repo=>repo.netWorth.list())});
 if(session.state!=='ready')return null;
 const values=q.data??[],history=netWorthHistory(values,currency(code)),latest=history.at(-1),items=[...new Map(values.map(v=>[v.itemId,v])).values()];
 const refresh=()=>client.invalidateQueries({queryKey:['net-worth']});
 async function save(){setBusy(true);setError('');try{if(date>localDay())throw new Error('Use a valuation date up to today.');const existing=items.find(v=>v.itemId===item),value=parseDecimal(amount,currency(existing?.currency??code));await session.run(repo=>repo.netWorth.save({id:crypto.randomUUID(),itemId:item||crypto.randomUUID(),name:existing?.name??name,kind:existing?.kind??kind,currency:value.currency,date,minor:value.minor.toString()}));await refresh();setOpen(false);setAmount('');setName('');}catch(e){setError(e instanceof Error?e.message:'The value could not be saved.');}finally{setBusy(false);}}
 const ceiling=history.reduce((m,p)=>{const n=BigInt(p.net),a=n<0n?-n:n;return a>m?a:m;},1n);
 const plotY=(value:string)=>{const unit=Number(displayRatio(value,ceiling.toString()));return 100-unit*90/1000000;};
 const first=Date.parse(history[0]?.date??localDay()),last=Date.parse(latest?.date??localDay());
 const plotX=(date:string)=>10+(Date.parse(date)-first)*980/Math.max(1,last-first);
 const points=history.flatMap((p,i)=>i?[`${plotX(p.date)},${plotY(history[i-1]!.net)}`,`${plotX(p.date)},${plotY(p.net)}`]:[`${plotX(p.date)},${plotY(p.net)}`]);
 return <section className="stack"><h2>Recorded net worth</h2><p>Assets minus liabilities you record here. Imported account balances are not added automatically. Include each holding once; values remain estimates until you update them.</p><label className="input-label">Net worth currency<select value={code} onChange={e=>setCode(e.target.value)}>{Object.keys(currencyDigits).map(c=><option key={c}>{c}</option>)}</select></label>{latest?<><Row trailing={<Amount value={money(BigInt(latest.net),currency(code))} context="recorded net worth"/>}>Latest recorded total<p className="meta">As of {latest.date} · includes earlier valuations</p></Row>{history.length===1?<p className="meta">One valuation date recorded. Add a value on another date to see how your total changes.</p>:<><Row trailing={<Amount value={money(ceiling,currency(code))} context="net worth scale maximum"/>}>Scale maximum</Row><svg viewBox="0 0 1000 200" role="img" aria-label="Recorded net worth at valuation dates. Earlier item values are carried forward; this is not a live market valuation."><line x1="0" y1="100" x2="1000" y2="100" stroke="var(--border-default)"/><polyline points={points.join(' ')} stroke="var(--accent)" fill="none" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{history.map(p=><circle key={p.date} cx={plotX(p.date)} cy={plotY(p.net)} r="3" fill="var(--accent)"/>)}</svg><Row trailing={<Amount value={money(-ceiling,currency(code))} context="net worth scale minimum"/>}>Scale minimum · zero is the centre</Row><p className="meta">{history[0]?.date} to {latest.date}</p></>}<details><summary>Valuation dates and source values</summary>{history.map(p=><section key={p.date}><Row trailing={<Amount value={money(BigInt(p.net),currency(code))} context={`recorded net worth ${p.date}`}/>}>{p.date}</Row>{p.items.map(v=><Row key={v.id} trailing={<Amount value={money(BigInt(v.minor)*(v.kind==='liability'?-1n:1n),v.currency)} context={v.name}/>}>{v.name}<p className="meta">{v.kind} · valued {v.date}</p></Row>)}</section>)}</details></>:<p>No {code} valuations recorded.</p>}<Button disabled={q.isPending} onClick={()=>{setItem('');setError('');setOpen(true);}}>Record a value</Button><details><summary>Manage recorded values</summary>{values.map(v=><Row key={v.id} trailing={<div className="stack"><Amount value={money(BigInt(v.minor),v.currency)} context={v.name}/><Button onClick={()=>setRemove(v.id)}>Remove</Button></div>}>{v.name} · {v.date}</Row>)}</details>{q.error&&<p role="alert">Recorded values could not be read.</p>}
 {open&&<Sheet title="Record an asset or liability" onClose={()=>{if(!busy)setOpen(false);}}><div className="stack"><label className="input-label">Item<select value={item} onChange={e=>setItem(e.target.value)}><option value="">New item</option>{items.map(v=><option key={v.itemId} value={v.itemId}>{v.name} · {v.currency}</option>)}</select></label>{!item&&<><Input label="Item name" value={name} maxLength={80} onChange={e=>setName(e.target.value)}/><label className="input-label">Type<select value={kind} onChange={e=>setKind(e.target.value as 'asset'|'liability')}><option value="asset">Asset</option><option value="liability">Liability</option></select></label><p>Currency: {code}</p></>}<Input label="Valuation date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Input label="Positive value or amount owed" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/>{error&&<p role="alert">{error}</p>}<Button disabled={busy} onClick={()=>void save()}>Save value</Button></div></Sheet>}
 {remove&&<Sheet title="Remove this valuation?" onClose={()=>setRemove(null)}><p>Only this recorded value is removed. Other dates and ledger transactions stay intact.</p><Button disabled={busy} onClick={()=>{setBusy(true);void session.run(repo=>repo.netWorth.remove(remove)).then(refresh).then(()=>setRemove(null)).catch(()=>setError('The valuation could not be removed.')).finally(()=>setBusy(false));}}>Remove value</Button>{error&&<p role="alert">{error}</p>}</Sheet>}
 </section>;
}
