import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {currency,format,money} from '../../core/money';
import {Amount,Button,Input,Row} from '../design/primitives';
import {useSession} from '../session';
export function Refunds({id,credit}:{id:string;credit:boolean}){
 const session=useSession(),client=useQueryClient(),[editing,setEditing]=useState(false),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[removing,setRemoving]=useState(false);
 const q=useQuery({queryKey:['refund',id],enabled:session.state==='ready',queryFn:()=>session.run(r=>r.refunds.read(id))});
 const value=q.data;
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await client.invalidateQueries();setEditing(false);setRemoving(false);}catch(e){setError(e instanceof Error?e.message:'The refund link could not be changed.');}finally{setBusy(false);}}
 const rows=value?.candidates.filter(p=>(p.description+' '+p.date+' '+p.account).toLowerCase().includes(search.toLowerCase()))??[];
 return <section className="stack"><h3>{credit?'Refund link':'Refunds received'}</h3><p className="meta">Link an actual posted refund to its original purchase. The full credit counts once; the original statement amounts and dates stay intact.</p>
 {q.isPending?<p>Reading refund links…</p>:q.error?<p role="alert">Refund links could not be read. <Button onClick={()=>void q.refetch()}>Retry</Button></p>:<>
 {credit?<>{value?.saved&&!value.link&&<p role="alert">The saved link no longer matches its source payments. It is inactive until reviewed or removed.</p>}{value?.purchase&&<Row trailing={<Amount value={money(BigInt(value.purchase.minor),currency(value.purchase.currency))} context="original purchase"/>}>{value.purchase.description}<p>{value.purchase.date} · {value.purchase.account}</p></Row>}
 {!editing&&<Button onClick={()=>{setSelected(value?.purchase?.id??'');setEditing(true);setError('');}}>{value?.saved?'Review refund link':'Link this credit as a refund'}</Button>}
 {editing&&<><Input label="Find original purchase" value={search} onChange={e=>setSearch(e.target.value)}/><p className="meta">Matching currency and amount are not proof of a refund. Confirm only when the statement or receipt identifies the original purchase. One credit can link to one purchase; several partial refunds may link to the same purchase.</p><label className="input-label">Original purchase<select disabled={busy} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose purchase</option>{rows.slice(0,100).map(p=><option key={p.id} value={p.id}>{p.date} · {p.description} · {p.account} · {format(money(-BigInt(p.minor),currency(p.currency)))}</option>)}</select></label>{rows.length>100&&<p>Showing 100 purchases. Narrow the search to find another.</p>}{!rows.length&&<p>No eligible purchase. Import its statement first or leave this credit unlinked.</p>}<Button disabled={busy||!selected} onClick={()=>void act(()=>session.run(r=>r.refunds.save(id,selected)))}>Confirm refund link</Button><Button disabled={busy} onClick={()=>setEditing(false)}>Cancel refund linking</Button></>}
 {value?.saved&&<Button disabled={busy} onClick={()=>setRemoving(true)}>Remove refund link</Button>}</>:<>{value?.refunds.length?<>{value.refunds.map(r=><Row key={r.id} trailing={<Amount value={money(BigInt(r.minor),currency(r.currency))} context="linked refund"/>}>{r.description}<p>{r.date} · {r.account}</p></Row>)}<Row trailing={<Amount value={money(BigInt(value.remaining!),currency(value.refunds[0]!.currency))} context="purchase amount after linked refunds"/>}>Purchase amount after linked refunds</Row></>:<p>No confirmed refund linked to this purchase.</p>}</>}
 </>}{removing&&<><p>Remove this link? Both statement transactions remain.</p><Button disabled={busy} onClick={()=>void act(()=>session.run(r=>r.refunds.remove(id)))}>Confirm remove refund link</Button><Button disabled={busy} onClick={()=>setRemoving(false)}>Keep refund link</Button></>}{error&&<p role="alert">{error}</p>}</section>;
}
